### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [divamgupta/image-segmentation-keras#1]
Can you please share the pretrained model?

**Comment by divamgupta** [comment]
For which datasets do you need a pretrained model?

**Comment by Zumbalamambo** [comment]
I need model for semantic segmentation using vgg_segnet

**Comment by raghavgurbaxani** [comment]
Hi @divamgupta , could you share the pretrained weights for one of the VGG based models.

Thanks. :)

**Comment by divamgupta** [comment]
Pretrained model added. Pls refer to the readme.
