### ISSUE TITLE
data-augmentation not working

### ISSUE THREAD

**Issue by tinalegre** [divamgupta/image-segmentation-keras#100]
there's a bug in following [line](https://github.com/divamgupta/image-segmentation-keras/blob/8ebe98bad4091f8690632c0cf0f25c078ed3788a/keras_segmentation/data_utils/data_loader.py#L128) in the image_segmentation_generator function. whenever you set the augmentation to true, your code won't work. you should change it with:
`im , seg[:,:,0] = augment_seg( im , seg[:,:,0] )`

**Comment by divamgupta** [comment]
Thanks for pointing it out. Ive fixed the line.
