### ISSUE TITLE
How to change segmentation output size?

### ISSUE THREAD

**Issue by despotovski01** [divamgupta/image-segmentation-keras#103]
Hello,

I'm using the vgg_unet model for image segmentation, but the predicted ground truths are always scaled down to half the width and half the height of the original dimensions. The out images are the correct sizes though. Can you tell me how to set the output size to be the exact size of the input images?

Thank you,
Aleksandar

**Comment by divamgupta** [comment]
You can add more upsampling layers  in the decoder. Or you can simply interpolate the final output to  your desired resolution.

**Comment by GGDRriedel** [comment]
How would I do that? Is there a function to access the decoder?
