### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by hugogithubcount** [divamgupta/image-segmentation-keras#106]
got this error when i try to train the model:
"AssertionError: dataset1//images_prepped_train\0001TP_006690.png is present in dataset1//images_prepped_train// but 0001TP_006690.png is not found in dataset1//annotations_prepped_train/ . Make sure annotation image are in .png"

all files extensions in "dataset1//annotations_prepped_train/" are .png

**Comment by ammaradam** [comment]
Try replacing the last forward slash for train_annotations path with double backslash instead.

Replace this section:

model.train( 
    train_images =  "dataset1/images_prepped_train/",
    train_annotations = "dataset1/annotations_prepped_train\\",
    checkpoints_path = "/tmp/vgg_unet_1" , epochs=5
)

**Comment by hugogithubcount** [comment]
> Try replacing the last forward slash for train_annotations path with double backslash instead.
> 
> Replace this section:
> 
> model.train(
> train_images = "dataset1/images_prepped_train/",
> train_annotations = "dataset1/annotations_prepped_train\",
> checkpoints_path = "/tmp/vgg_unet_1" , epochs=5
> )
thank you very much, it worked out well.
