### ISSUE TITLE
dataset annotations prepped images are black

### ISSUE THREAD

**Issue by chensteven** [divamgupta/image-segmentation-keras#108]
I just downloaded the dataset and the images in the annotations_prepped_train/test are all black. What exactly are they suppose to be?

**Comment by thezaza101** [comment]
They arnt black, the pixel values are just low. Each unique pixel value between 0 and 255 represent a different class. You can read it in and show it using matplotlib, it will make it more clear. i.e.

![Untitled](https://user-images.githubusercontent.com/27200279/64929183-0bef3280-d866-11e9-94e7-f3252031ed12.png)
