### ISSUE TITLE
cannot import name transfer_weights

### ISSUE THREAD

**Issue by fizaict** [divamgupta/image-segmentation-keras#109]
When i tried to fine tune a model with 10 classes I am getting this error

 

> from keras_segmentation.models.model_utils import transfer_weights 

> ImportError: cannot import name transfer_weights

Please help me fix this issue asap.

**Comment by divamgupta** [comment]
At which commit of the repo are you using?

**Comment by fizaict** [comment]
Sorry I did not get your point. I simply installed the `keras_segmentation` module through CLI and started following your tutorial. It is working fine but in the end during fine tune it showed me the error

from keras_segmentation.models.model_utils import transfer_weights

ImportError: cannot import name transfer_weights

**Comment by divamgupta** [comment]
If you installed `keras_segmentation` via pip then `transfer_weights` is not available yet. You can use setup.py to install the latest version of the module.

**Comment by fizaict** [comment]
@divamgupta thank u so much for such timely response

**Comment by fizaict** [comment]
@divamgupta Can you please further explain that what will happen when you try to fine tune the model? Is it important to fine tune the model? Your help will be really appreciated.

**Comment by divamgupta** [comment]
You might get better results if you have lesser data. You can read more [here](https://flyyufelix.github.io/2016/10/03/fine-tuning-in-keras-part1.html)

**Comment by Danfoa** [comment]
> If you installed `keras_segmentation` via pip then `transfer_weights` is not available yet. You can use setup.py to install the latest version of the module.

I installed by cloning and running `setup.py install`, the import error persist, did something change in the latest commits?
