### ISSUE TITLE
Vgg16 unet output shape

### ISSUE THREAD

**Issue by gepo1989** [divamgupta/image-segmentation-keras#110]
Is there a particular reason that the (reshaped) output width and height in vgg16 unet are half of the input height and width? I think it is similar for other models.
How would you modify the network to get the equal input and output shapes?
Thanks in advance

**Comment by divamgupta** [comment]
This is because there are more downsampling operations than upsampling. You can add another Upsampling layer to the decoder to get equal input and output shape.

**Comment by gitunit** [comment]
why would one want less upsampling operations?
