### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.image' has no attribute 'resize__images'

### ISSUE THREAD

**Issue by SreenijaK** [divamgupta/image-segmentation-keras#126]
Hi,
I'm using tensorflow Version: 1.13.1,  keras Version: 2.3.0 ,
I get the following error when i try to test the pre trained models.
File "/veImgSegmentation/lib/python3.5/site-packages/keras_segmentation-0.2.0-py3.5.egg/keras_segmentation/models/_pspnet_2.py", line 38, in call
AttributeError: module 'tensorflow._api.v1.image' has no attribute 'resize__images'

**Comment by PallawiSinghal** [comment]
> Hi,
> I'm using tensorflow Version: 1.13.1, keras Version: 2.3.0 ,
> I get the following error when i try to test the pre trained models.
> File "/veImgSegmentation/lib/python3.5/site-packages/keras_segmentation-0.2.0-py3.5.egg/keras_segmentation/models/_pspnet_2.py", line 38, in call
> AttributeError: module 'tensorflow._api.v1.image' has no attribute 'resize__images'

May I know how did you solve this?

**Comment by PallawiSinghal** [comment]
May I know how did you solve this?
