### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by amd-lthakur** [divamgupta/image-segmentation-keras#128]
I am trying to load pspnet pretrained model and encountered the said error.
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'
Could please guide me how resolve this?
Config: Windows10
using Juyter notebook
tensorflow version: 2.0.0
code source : https://github.com/divamgupta/image-segmentation-keras
The code used to reproduce the issue is:
import keras_segmentation
model = keras_segmentation.pretrained.pspnet_101_voc12()

**Comment by vasylcf** [comment]
Hi @amd-lthakur , I have the same problem.
My solution is to downgrade TF version to 1.15

**Comment by amd-lthakur** [comment]
ok... thanq for your response :).
I downgraded keras and it worked for me.
