### ISSUE TITLE
Bad prediction even with high training and validation accuracy

### ISSUE THREAD

**Issue by Alsen57** [divamgupta/image-segmentation-keras#132]
hey guys,

i am using this code for image segmentation:

`from keras_segmentation.models.unet import unet

model = unet(n_classes=3)
model.train(n_classes=3,
    train_images =  "/content/Training/images",
    train_annotations = "/content/Training/labels",
    checkpoints_path = "/content/checkpoints" , epochs=1,validate=True,val_images="/content/Test/images",val_annotations="/content/Test/labels")
`
Epoch 1/1
512/512 [==============================] - 252s 492ms/step - loss: 0.1199 - accuracy: 0.9728 - val_loss: 7.3933e-05 - val_accuracy: 1.0000
saved  /content/checkpoints.model.0
Finished Epoch 0

I have high accuracies but bad prediction. I tried different models. All give me the same result.

Image
![index](https://user-images.githubusercontent.com/46636017/68777536-1a718480-0632-11ea-9d7e-87e332ffdeab.jpg)
Label
![index](https://user-images.githubusercontent.com/46636017/68777586-2bba9100-0632-11ea-9db9-78203ce63fb5.png)
Prediction
![prediction](https://user-images.githubusercontent.com/46636017/68777590-2d845480-0632-11ea-897c-a64e466a56c4.png)

**Comment by divamgupta** [comment]
Could  you try model.evaluate_segmentation (refer to the readme )?

**Comment by Alsen57** [comment]
> Could you try model.evaluate_segmentation (refer to the readme )?

**Comment by Alsen57** [comment]
print(model.evaluate_segmentation(inp_inmges="/content/Test/images"  , annotations="/content/Test/labels" ) )

I tried but all i get is is a not implemented errror : 
`AssertionError                            Traceback (most recent call last)
<ipython-input-14-2c650eeac8c0> in <module>()
----> 1 print(model.evaluate_segmentation(inp_inmges="/content/Test/images"  , annotations="/content/Test/labels" ) )

/usr/local/lib/python3.6/dist-packages/keras_segmentation/predict.py in evaluate(model, inp_inmges, annotations, checkpoints_path)
    109 def evaluate( model=None , inp_inmges=None , annotations=None , checkpoints_path=None ):
    110 
--> 111         assert False , "not implemented "
    112 
    113         ious = []

AssertionError: not implemented `

**Comment by divamgupta** [comment]
You would need to use the latest master version of the repo rather than the one on pypi.

**Comment by Alsen57** [comment]
> 
> 
> You would need to use the latest master version of the repo rather than the one on pypi.

hi i used now the directly downloaded github version but i still get bad prediction
![Unbenannt](https://user-images.githubusercontent.com/46636017/69231054-b5191880-0b88-11ea-8e4f-55d58246c594.PNG)

**Comment by divamgupta** [comment]
Maybe the dataset is not pre-processed properly.  Could you share a few Images / Annotations of the  pre-processed dataset by zipping them.

**Comment by reem90** [comment]
I have the same problem. I was testing the visualize_dataset file. The function _get_colored_segmentation_image() always return image where all pixels have the same color. 
did you solve your problem? if yes, kindly share.

**Comment by Yunaka12** [comment]
I have the same problem.
In my training datasets, the acc is about 99%, but when I use evaluate_segmentation for test datasets, the IoU is about 0.03%.

My training condition is this：
The number of epochs is 10, the acc is about 99%.
The number of class is two. One is a object, the other is background.
The number of training data image is 5000.
Annotation image file format is PNG, but training image file format is JPG.

Sorry for my bad English.
Best Regards.

**Comment by reem90** [comment]
I had the same issue and I solved it as follows: 
First of all, the labeled image generated from labelme tool has several channels. While the labeled image used in image-segmentation-keras has one channel. You can check that using Matlab. So, to convert all the labeled images from multiple channels to a single channel, create a small script in Matlab to read the png labeled images and save it again as png. It will directly save it as one channel image. Use these images for training. The generated images will look like black images. just try in a small dataset to make sure that it works. 

It worked with me. 

Best Regards,

**Comment by TharinduMoraDs** [comment]
> I had the same issue and I solved it as follows:
> First of all, the labeled image generated from labelme tool has several channels. While the labeled image used in image-segmentation-keras has one channel. You can check that using Matlab. So, to convert all the labeled images from multiple channels to a single channel, create a small script in Matlab to read the png labeled images and save it again as png. It will directly save it as one channel image. Use these images for training. The generated images will look like black images. just try in a small dataset to make sure that it works.
> 
> It worked with me.
> 
> Best Regards,

That's true. Now working fine. Thanks, bro

**Comment by gitunit** [comment]
im also getting bad predictions despite a high accuracy and low loss. all images that have been used for training are single channel. 

the function "evaluate_segmentation" throws error that it's not implemented (maybe this should be highlighted in the README?)

**Comment by SreenijaK** [comment]
> I had the same issue and I solved it as follows:
> First of all, the labeled image generated from labelme tool has several channels. While the labeled image used in image-segmentation-keras has one channel. You can check that using Matlab. So, to convert all the labeled images from multiple channels to a single channel, create a small script in Matlab to read the png labeled images and save it again as png. It will directly save it as one channel image. Use these images for training. The generated images will look like black images. just try in a small dataset to make sure that it works.
> 
> It worked with me.
> 
> Best Regards,

@reem90 does this mean grayscaling of the image?. can we use the python for the same?

**Comment by SreenijaK** [comment]
> I had the same issue and I solved it as follows:
> First of all, the labeled image generated from labelme tool has several channels. While the labeled image used in image-segmentation-keras has one channel. You can check that using Matlab. So, to convert all the labeled images from multiple channels to a single channel, create a small script in Matlab to read the png labeled images and save it again as png. It will directly save it as one channel image. Use these images for training. The generated images will look like black images. just try in a small dataset to make sure that it works.
> 
> It worked with me.
> 
> Best Regards,
i tried the following in python. Would this work? @reem90  @divamgupta  @TharinduMoraDs 
from skimage.color import rgb2gray
gray = rgb2gray(im);

**Comment by zedka10** [comment]
Can you please tell me how to solve this issue. I'm getting a blue image for prediction. I checked the @reem90 solution but i dont have matlab.
Best regards,

**Comment by TharinduMoraDs** [comment]
> > I had the same issue and I solved it as follows:
> > First of all, the labeled image generated from labelme tool has several channels. While the labeled image used in image-segmentation-keras has one channel. You can check that using Matlab. So, to convert all the labeled images from multiple channels to a single channel, create a small script in Matlab to read the png labeled images and save it again as png. It will directly save it as one channel image. Use these images for training. The generated images will look like black images. just try in a small dataset to make sure that it works.
> > It worked with me.
> > Best Regards,
> 
> i tried the following in python. Would this work? @reem90 @divamgupta @TharinduMoraDs
> from skimage.color import rgb2gray
> gray = rgb2gray(im);

I followed these steps:

1 - label the image (I used labelMe)

2 - Label Images has more than two colours. It depends on the number of areas which you wanted to segment. Assume that the image has one object to segmented.  

3 - So, After labelling the image, It has two colours areas. The object is shown in one colour and background is shown in another colour.

4 - Now, convert the label image into a grayscale image.

5- Now, the object has a grey value and background has a different gray value.

_Assume that, the object gray value is 38 and the background gray value is 78_
6 - Now, convert the gray image into classes. The class values start at 1. (Change the pixel values into class values)
      _if(value == 38 ):_
              _Image[y, x] = 1_
      _elsif( value == 78):_
              _Image[y, x] = 2_
_Likewise, you have to give class values for all the area which you wanted to segment._
All annotation images should have the same number of classes. 

7 - Finally you receive the annotation image. (It is an almost back image.)

**Comment by amil-rp-work** [comment]
@TharinduMoraDs  
Hey can you please share the python code for the same. I am unfortunately not able to get grayscale image( image of single channel) and with values as 0 or 1.
