### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zldyd** [divamgupta/image-segmentation-keras#133]
my anaconda can't work after install this garbage ,and can't be fixed

**Comment by divamgupta** [comment]
Hi, thanks for the interest in our project. Could you please elaborate the
issues you are facing?

**Comment by lborke** [comment]
I have succesfully installed this repo.
The best way is to use a Docker container.
In my case I am using a Tensorflow 1.14 image.

sudo docker run --gpus all -it \
  -v ~/app:/app \
  -v ~/data:/data \
  tensorflow/tensorflow:1.14.0-gpu-py3 bash

After that I can install opencv + Keras and finally this repo.

I must say, the instructions in the README.md are not quite complete.
At least in the case of a Docker Tensorflow container.

I will try to make a PR to this repo with the current and successful instructions how to get this repo to work with an official TF container.

Using Docker you can simply delete the current container and try another one without messing up your current Ubuntu installation.

**Comment by lborke** [comment]
I highly discourage everybody to use:
```
sudo apt-get install python-opencv
```
as shown in the [readme](https://github.com/divamgupta/image-segmentation-keras/blob/master/README.md)

```
apt-get update
apt-get install -y libsm6 libxext6 libxrender-dev
pip install opencv-python
```

worked for me to get OpenCV to run!

I am using the Docker container:
> tensorflow/tensorflow:1.14.0-gpu-py3

**Comment by divamgupta** [comment]
Thanks @lborke  for the suggestion. I have updated the readme.
