### ISSUE TITLE
Problem when loading weights

### ISSUE THREAD

**Issue by eiraola** [divamgupta/image-segmentation-keras#134]
Hi, I was following this tutorial 

https://divamgupta.com/image-segmentation/2019/06/06/deep-learning-semantic-segmentation-keras.html

And everrything is great, but when I try to use:

from keras_segmentation import predict

predict( 
	checkpoints_path="checkpoints/vgg_unet_1", 
	inp="dataset_path/images_prepped_test/0016E5_07965.png", 
	out_fname="output.png" 
)

it says:

TypeError: 'module' object is not callable

The same happens with:

from keras_segmentation import predict_multiple

predict_multiple( 
	checkpoints_path="checkpoints/vgg_unet_1", 
	inp_dir="dataset_path/images_prepped_test/", 
	out_dir="outputs/" 
)

cannot import name 'predict_multiple'

cannot figure out what the problem is, any clues?

**Comment by eiraola** [comment]
Sorry it was a clumsy mistake, I forgot to put predict. before both functions :)

**Comment by MuhammadAsadJaved** [comment]
> Sorry it was a clumsy mistake, I forgot to put predict. before both functions :)

How did you resolve this issue? I have same problem.

**Comment by MuhammadAsadJaved** [comment]
> Sorry it was a clumsy mistake, I forgot to put predict. before both functions :)

What do you mean by "put predict before both function" ?

**Comment by MuhammadAsadJaved** [comment]
I have resolved this problem. we should import like this.
#Predict one picture
from keras_segmentation.predict import predict

predict(
checkpoints_path="/home/lab/image-segmentation-keras/checkpoints/pspnet50_ade20k.h5",
inp="images_test/input_image.jpg",
out_fname="output_image.png"
)

#Predict multiple images in a directory

from keras_segmentation.predict import predict_multiple

predict_multiple(
checkpoints_path="checkpoints/vgg_unet_1",
inp_dir="images_test/",
out_dir="outputs/"
)

**Comment by AKASH2907** [comment]
How did you resolve the problem of Checkpoint not found?? @MuhammadAsadJaved

**Comment by MuhammadAsadJaved** [comment]
Still have same issue, failed to resolve this issue

**Comment by AKASH2907** [comment]
You can just do it by the name of json file that is being saved in ur checkpoints directory. I figured it out after posting that's why deleted my comment.
If ur json file is saved as vgg-net_config.json just pass vgg-net and it will automatically pick up the best weight corresponding to that json file.

**Comment by MuhammadAsadJaved** [comment]
I downloaded pre trained weights manually and it only contains .h5 file.
How to get .config file?

**Comment by AKASH2907** [comment]
No, that's not what you have to do. As you train the model, weights get saved in the folder you specify with the specific name as vgg_unet_1.1, vgg_unet_1.2, etc. for each epoch and a json file named as vgg_unet_1_config.json. 
When you predict, give the checkpoints_path+vgg_unet_1 as an argument, then the network will start predicting.

**Comment by MuhammadAsadJaved** [comment]
Dear i didn’t train the model. I am just using pre trained model from repo
and run the example.

**Comment by AKASH2907** [comment]
If u dont train it, how r u expecting to get json file and all. What are you trying to give till now at the checkpoints path?? Read the readme file bro. 
Checkpoints can't be created without training.

**Comment by MuhammadAsadJaved** [comment]
Oh ok Thank you. but I was just try to run the demo using pre trained models as mentioned in the readme file. They did not mentioned to generate .json file. so i thought it only .h5 weights and rest of the files are already available.

**Comment by AKASH2907** [comment]
Nah for running also you need to have some checkpoint file and for that you need to train the model. Vgg_unet will automatically download and upload the weights for vgg16 network

**Comment by MuhammadAsadJaved** [comment]
OK. Thank you very much.

**Comment by YasmeenaAkhter** [comment]
after allocating the path for weights while training, I am getting this error
ValueError: listdir: embedded null character in path

Verifying training dataset
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-785d272b8f08> in <module>
----> 1 model.train(train_images,train_anno,checkpoints_path = "C:\\Users\\checkpoints\\vgg_unet_1.json" , epochs=5)

M:\anaconda\envs\YASMEENA\lib\site-packages\keras_segmentation\train.py in train(model, train_images, train_annotations, input_height, input_width, n_classes, verify_dataset, checkpoints_path, epochs, batch_size, validate, val_images, val_annotations, val_batch_size, auto_resume_checkpoint, load_weights, steps_per_epoch, val_steps_per_epoch, gen_use_multiprocessing, ignore_zero_class, optimizer_name, do_augment, augmentation_name)
    130         verified = verify_segmentation_dataset(train_images,
    131                                                train_annotations,
--> 132                                                n_classes)
    133         assert verified
    134         if validate:

M:\anaconda\envs\YASMEENA\lib\site-packages\keras_segmentation\data_utils\data_loader.py in verify_segmentation_dataset(images_path, segs_path, n_classes, show_all_errors)
    148                                 n_classes, show_all_errors=False):
    149     try:
--> 150         img_seg_pairs = get_pairs_from_paths(images_path, segs_path)
    151         if not len(img_seg_pairs):
    152             print("Couldn't load any data from images_path: "

M:\anaconda\envs\YASMEENA\lib\site-packages\keras_segmentation\data_utils\data_loader.py in get_pairs_from_paths(images_path, segs_path, ignore_non_matching)
     40     segmentation_files = {}
     41 
---> 42     for dir_entry in os.listdir(images_path):
     43         if os.path.isfile(os.path.join(images_path, dir_entry)) and \
     44                 os.path.splitext(dir_entry)[1] in ACCEPTABLE_IMAGE_FORMATS:

ValueError: listdir: embedded null character in path

**Comment by aneeqahazmat** [comment]
I am unable to read my training data , although training images and maska has data (image) still it gives assertion error.

**Comment by aneeqahazmat** [comment]
![16685830590972919382961245653886](https://user-images.githubusercontent.com/66739903/202112144-90cab097-5fa7-4db7-b876-67a527ebb996.jpg)


This is the error
