### ISSUE TITLE
Does Unet need relu activation?

### ISSUE THREAD

**Issue by off99555** [divamgupta/image-segmentation-keras#136]
Did you forget to put `activation='relu'` in these `Conv2D` layers or are they intended to be linear?
https://github.com/divamgupta/image-segmentation-keras/blob/736aad76d357d13c559c7105b91fc5828d4bb89a/keras_segmentation/models/unet.py#L78-L101

**Comment by divamgupta** [comment]
Thanks for pointing this out!
