### ISSUE TITLE
Unable to segment using pre-trained models

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [divamgupta/image-segmentation-keras#139]
Hi, I was following this tutorial

https://divamgupta.com/image-segmentation/2019/06/06/deep-learning-semantic-segmentation-keras.html

And everrything is great, but when I try to use:

import keras
import keras_segmentation 
from keras_segmentation import predict

predict( 
	checkpoints_path="checkpoints/vgg_unet_1", 
	inp="input_image.jpg", 
	out_fname="output_image.png" 
        )

it says:

TypeError: 'module' object is not callable

The same happens with:

from keras_segmentation import predict_multiple

predict_multiple( 
	checkpoints_path="checkpoints/vgg_unet_1", 
	inp_dir="images_test/", 
	out_dir="outputs/" 
)

cannot import name 'predict_multiple'

cannot figure out what the problem is, any clues?

**Comment by MuhammadAsadJaved** [comment]
I have resolved this problem. we should import like this. 
#Predict one picture 
from keras_segmentation.predict import predict

predict( 
	checkpoints_path="/home/littro/GANs/image-segmentation-keras/checkpoints/pspnet50_ade20k.h5", 
	inp="images_test/input_image.jpg", 
	out_fname="output_image.png" 
        )

#Predict multiple images in a directory 


from keras_segmentation.predict import predict_multiple

predict_multiple( 
	checkpoints_path="checkpoints/vgg_unet_1", 
	inp_dir="images_test/", 
	out_dir="outputs/" 
)

But now I face another problem. I have placed pspnet50_ade20k.h5 weights but the program still throw the error.   

     "Checkpoint not found."
AssertionError: Checkpoint not found.

I also tried after changing the path.
Note: I download weights manually.

**Comment by divamgupta** [comment]
Hi,

The snippet for pre-trained models mentioned in the readme should work.
