### ISSUE TITLE
Getting "Killed" ouput when trying to run training example

### ISSUE THREAD

**Issue by DawnMe** [divamgupta/image-segmentation-keras#14]
After following the README instructions, and running
`THEANO_FLAGS=device=gpu,floatX=float32  python  train.py  --save_weights_path=weights/ex1  --train_images="data/dataset1/images_prepped_train/"  --train_annotations="data/dataset1/annotations_prepped_train/"  --val_images="data/dataset1/images_prepped_test/"  --val_annotations="data/dataset1/annotations_prepped_test/"  --n_classes=10 --model_name="vgg_segnet"`

I'm getting the output
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-01-10 15:35:45.311492: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Killed
```

Trying to run the command with `sudo` give the same, minus the 'killed':
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

```

**Comment by SharathHuddar** [comment]
That's because you are using tensorflow backend. Use theano backend instead.
Install theano and use the following command
```
KERAS_BACKEND=theano THEANO_FLAGS=device=gpu,floatX=float32  python  train.py \
 --save_weights_path=weights/ex1 \
 --train_images="data/dataset1/images_prepped_train/" \
 --train_annotations="data/dataset1/annotations_prepped_train/" \
 --val_images="data/dataset1/images_prepped_test/" \
 --val_annotations="data/dataset1/annotations_prepped_test/" \
 --n_classes=10 \
 --input_height=320 \
 --input_width=640 \
 --model_name="vgg_segnet" 

```

**Comment by DawnMe** [comment]
@SharathHuddar  Thanks, it worked! 
Might be useful to add some more informative message rather than "Killed".

**Comment by divamgupta** [comment]
You see the message 'Killed' because the kernel kills your process. The is probably due to lack of resources.

Look at:
https://stackoverflow.com/questions/726690/who-killed-my-process-and-why

And it is not recommended to train deep learning models without a GPU. It would be extremely slow.

**Comment by horo2016** [comment]
it maybe memory overrun  ,smaller the picture size
