### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/vgg_unet_1_config.json'

### ISSUE THREAD

**Issue by winynfuck** [divamgupta/image-segmentation-keras#147]
The following codes:
from keras_segmentation.models.unet import vgg_unet
import os 
os.chdir('E:\图像分割')
#从Keras-segmentation API
model = vgg_unet(n_classes=51 ,  input_height=416, input_width=608  )

model.train(
    train_images =  "dataset1/images_prepped_train/",
    train_annotations = "dataset1/annotations_prepped_train/",
    checkpoints_path = "/tmp/vgg_unet_1" , epochs=5
)

out = model.predict_segmentation(
    inp="dataset1/images_prepped_test/0016E5_07965.png",
    out_fname="/tmp/out.png"
)

import matplotlib.pyplot as plt
plt.imshow(out)

# evaluating the model 
print(model.evaluate_segmentation( inp_images_dir="dataset1/images_prepped_test/"  , annotations_dir="dataset1/annotations_prepped_test/" ) )

who can tell me where is the file vgg_unet_1_config.json

**Comment by thezaza101** [comment]
it should be in the checkpoints_path folder, it gets created as soon as training starts

**Comment by forest44** [comment]
the tmp folder should exists. On Windows, you have to write "**.**/tmp/vgg_unet_1"
