### ISSUE TITLE
How to predict when using model.save()

### ISSUE THREAD

**Issue by reem90** [divamgupta/image-segmentation-keras#149]
The code is implemented to predict images from folder when saving the model and the weights using `model.save_weights(checkpoints_path+ "." + str(ep)). `
Hence, the prediction depends only on the checkpoints 
`predict(inp=args.input_path, out_fname=args.output_path,                          checkpoints_path=args.checkpoints_path)`

Can I use the same prediction function If I want to use model.save() instead of model.sace_weights() ?

**Comment by divamgupta** [comment]
Currently this is not supported. You can use `model_from_checkpoint_path`  function if you don't want to instantiate the model yourself.
