### ISSUE TITLE
How to draw mask on rgb image

### ISSUE THREAD

**Issue by basit26374** [divamgupta/image-segmentation-keras#159]
I am working on image segmentation problem and I would like to visualize the mask on RGB input image. But model.predict_segmentation() give only processed image
`out= model.predict_segmentation(
    inp="sample_1.png",
    out_fname="out.png"
)`

Is there any way that model.predict_segmentation () gives masked images
for example 
`out, masked_image = model.predict_segmentation(
    inp="sample_1.png",
    out_fname="out.png"
)`

like this 

[https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.analyticsvidhya.com%2Fblog%2F2019%2F07%2Fcomputer-vision-implementing-mask-r-cnn-image-segmentation%2F&psig=AOvVaw1SALqaHHsbmMcDpb87yLOE&ust=1581773169047000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJCwubKS0ecCFQAAAAAdAAAAABAD](url)

![index](https://user-images.githubusercontent.com/30195365/74535484-bd9aa880-4f57-11ea-878b-9d6a2727b0de.jpeg)

**Comment by divamgupta** [comment]
You can. Check out the predict function in the dev branch. 

Using pip, you can install the dev version using the following command

`pip install --upgrade https://github.com/divamgupta/image-segmentation-keras/archive/dev.zip`

**Comment by Philliec459** [comment]
This pip install did not work for me. Is it still there?

**Comment by divamgupta** [comment]
The dev branch is deleted and merged to the master. You should find these functionality in the master. Refer to the predict function.
