### ISSUE TITLE
AssertionError: C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplit\0.png is present in C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplit/ but 0.png is not found in C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplitMask/ . Make sure annotation image are in .png

### ISSUE THREAD

**Issue by furkan59** [divamgupta/image-segmentation-keras#160]
AssertionError: C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplit\0.png is present in C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplit/ but 0.png is not found in C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplitMask/ . Make sure annotation image are in .png

but actually file exists in here. What can I do ? annotation image exists in locaiton 

"C:\Users\furkam\PycharmProjects\PyhtonTest1\Root\YapayZeka\Dressing\analiticmodel\results\trainSplitMask\0.png"
I have a file like that.

I am running this code 

`from keras_segmentation.models.unet import vgg_unet
import os

testDir = "C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/test/1/"
output = "C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/preds/"

train_imagesPath        = "C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplit/"
train_annotationsPath   = "C:/Users/furkam/PycharmProjects/PyhtonTest1/Root/YapayZeka/Dressing/analiticmodel/results/trainSplitMask/"
weightsName = "vgg_unet.h5"

model = vgg_unet(n_classes=2 ,  input_height=256, input_width=256)

model.train(
    train_images =  train_imagesPath,
    train_annotations = train_annotationsPath,
    checkpoints_path = "/tmp/vgg_unet_1" , epochs=5
)
model.save_weights(weightsName)
file_list = os.listdir(testDir)

count = 0
for file in file_list:   
    newfileName = output + str(count) + ".png"
    inputFileName = testDir + file
    print(inputFileName)
    model.predict_segmentation(inp=inputFileName,out_fname=newfileName)
    count = count+1

`

**Comment by divamgupta** [comment]
This error would not occur in the latest version.
