### ISSUE TITLE
are models trained really from scratch?

### ISSUE THREAD

**Issue by gitunit** [divamgupta/image-segmentation-keras#163]
i've been diving through the code and noticed that models seem to be trained not really from scratch but load some pretrained weights. any plans to support learning from scratch? i guess setting another "pretrained" default for the get_.._encoder function would do it, correct?

**Comment by AndresPrada** [comment]
As I've seen, if you don't do transfer learning, the encoders use pretrained weights from `imagenet`. If you want to train from scratch, this is assigning random weights to the encoder, you can just set the pretrained parameter as `None`. The decoders, as I understand, do not have any pretrained weights.

**Comment by gitunit** [comment]
yes, i meant the encoders. using pretrained weights from imagenet is set as default and never changes as far as i've seen.

**Comment by AndresPrada** [comment]
what do you mean as "never changes"? don't they get updated when you train them?

**Comment by gitunit** [comment]
i mean that the parameter is never changed, it always is "imagenet" and thus it always uses pretrained weights for the encoder. i know how to change it in code but there is no parameter which would change that by library "API". by mentioning this, i wanted to start a discussion if that is something worth adding the list of "train" parameters in my initial post.

**Comment by gitunit** [comment]
just closed? no comment?
