### ISSUE TITLE
Error whlie calling the evaluate

### ISSUE THREAD

**Issue by rich-pel** [divamgupta/image-segmentation-keras#165]
Hello,
I get this error, and I can't figure out why it's happening. 

This is the Code:
```print(model.evaluate_segmentation( inp_images_dir="ScaledData\\img_test"  , annotations_dir="ScaledData\\seg_test" ) )```

This is the Errormassage:
**Exception has occurred: TypeError**
*evaluate() got an unexpected keyword argument 'inp_images_dir'*

I don't understand what's happening here?

keras_segmentation/models/model_utils.py
model.evaluate_segmentation= MethodType(predict_multiple, model)

**Comment by khairulezwan** [comment]
Have you found the solution for this error?
@divamgupta

**Comment by khairulezwan** [comment]
Found the error, you need to pip install the latest keras segmentaiton ver.
It works fine after that

**Comment by khairulezwan** [comment]
pip install --upgrade git+https://github.com/divamgupta/image-segmentation-keras
