### ISSUE TITLE
Evaluate function

### ISSUE THREAD

**Issue by khairulezwan** [divamgupta/image-segmentation-keras#168]
I have an issue on evaluate method

TypeError                                 Traceback (most recent call last)
<ipython-input-9-c38701810629> in <module>
      1 # evaluating the model
----> 2 print(model.evaluate_segmentation( inp_images_dir="dataset/val_img/Val_00_19.png"  , annotations_dir="dataset/val_seg/Val_00_19.png" ) )

TypeError: evaluate() got an unexpected keyword argument 'inp_images_dir'

**Comment by divamgupta** [comment]
Hi,

Are you using the latest master version of the library or the pip release?
It should work on the master version.
You can install the latest version by : 

`pip install git+https://github.com/divamgupta/image-segmentation-keras`

**Comment by phuongchi911** [comment]
> Hi,
> 
> Are you using the latest master version of the library or the pip release?
> It should work on the master version.
> You can install the latest version by :
> 
> `pip install git+https://github.com/divamgupta/image-segmentation-keras`

hi @divamgupta  i got same issue too thought i did install the latest version. I tried to google to fix error but seems not working. May you take a look? thanks a lot

![image](https://user-images.githubusercontent.com/43133053/75781177-b537cf80-5d97-11ea-8565-aaeb79a85c5d.png)

**Comment by divamgupta** [comment]
If the package is installed from pypi first then it is not upgraded when you install the master unless you use `--upgrade` option. Maybe that is causing the issue.

`pip install --upgrade git+https://github.com/divamgupta/image-segmentation-keras`

**Comment by khairulezwan** [comment]
> Hi,
> 
> Are you using the latest master version of the library or the pip release?
> It should work on the master version.
> You can install the latest version by :
> 
> `pip install git+https://github.com/divamgupta/image-segmentation-keras`

hi after installing the latest release ive been able to make the evaluate function work. Thank you for replying
