### ISSUE TITLE
VGGSegNet - incorrect implementation

### ISSUE THREAD

**Issue by hav4ik** [divamgupta/image-segmentation-keras#17]
The [VGGSegNet][1] model uses simple `UpSampling2d`, while the whole idea of `SegNet` architecture is to pass max-pooling indices to the upsampling layers (index-based upsampling).

[1]: https://github.com/divamgupta/image-segmentation-keras/blob/master/Models/VGGSegnet.py

**Comment by divamgupta** [comment]
This is actually an implementation of SegNet-Basic where the authors use simple UpSampling.
SegNet-Basic was earlier termed SegNet in an older archival version of the paper.
