### ISSUE TITLE
Libraries version

### ISSUE THREAD

**Issue by hontarenkoYana** [divamgupta/image-segmentation-keras#174]
Can you please tell what version of library from requirements needed? After installing latest versions I can't load pretrained models. Error: 
`from keras.backend import tf as ktf`
`ImportError: cannot import name 'tf'`

My libraries version
Keras==2.3.1
numpy==1.18.1
opencv-python==4.2.0.32
tensorflow-gpu==2.1.0

**Upgrade:** I found that you requirements was keras==2.0. I uninstall old libraries and now my libraries are: 
Keras==2.0.0
numpy==1.18.1
opencv-python==4.2.0.32
tensorflow-gpu==2.1.0
Error: 
`graph = tf.get_default_graph()`
`AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`

**Comment by ashcrok** [comment]
I have encountered the same issue. Any updates?

**Comment by Billy1900** [comment]
why not change an older version of tensorflow, like 1.14.0?

**Comment by JaledMC** [comment]
> Can you please tell what version of library from requirements needed? After installing latest versions I can't load pretrained models. Error:
> `from keras.backend import tf as ktf`
> `ImportError: cannot import name 'tf'`
> 
> My libraries version
> Keras==2.3.1
> numpy==1.18.1
> opencv-python==4.2.0.32
> tensorflow-gpu==2.1.0
> 
> **Upgrade:** I found that you requirements was keras==2.0. I uninstall old libraries and now my libraries are:
> Keras==2.0.0
> numpy==1.18.1
> opencv-python==4.2.0.32
> tensorflow-gpu==2.1.0
> Error:
> `graph = tf.get_default_graph()`
> `AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`

@hontarenkoYana, about the libraries you have pointed, this setup works on my machine with conda: 
> Keras==2.3.1
> numpy==1.17.2
> opencv-python==4.1.0
> tensorflow-gpu==1.14.0

As @Billy1900 said, tf 1.14 works fine. You can use the [dockerfile](https://github.com/divamgupta/image-segmentation-keras/blob/master/docker/Dockerfile) of this repo if installation dependencies persists.

**Comment by hontarenkoYana** [comment]
> > Can you please tell what version of library from requirements needed? After installing latest versions I can't load pretrained models. Error:
> > `from keras.backend import tf as ktf`
> > `ImportError: cannot import name 'tf'`
> > My libraries version
> > Keras==2.3.1
> > numpy==1.18.1
> > opencv-python==4.2.0.32
> > tensorflow-gpu==2.1.0
> > **Upgrade:** I found that you requirements was keras==2.0. I uninstall old libraries and now my libraries are:
> > Keras==2.0.0
> > numpy==1.18.1
> > opencv-python==4.2.0.32
> > tensorflow-gpu==2.1.0
> > Error:
> > `graph = tf.get_default_graph()`
> > `AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`
> 
> @hontarenkoYana, about the libraries you have pointed, this setup works on my machine with conda:
> 
> ```
> Keras==2.3.1
> numpy==1.17.2
> opencv-python==4.1.0
> tensorflow-gpu==1.14.0
> ```
> 
> As @Billy1900 said, tf 1.14 works fine. You can use the [dockerfile](https://github.com/divamgupta/image-segmentation-keras/blob/master/docker/Dockerfile) of this repo if installation dependencies persists.

Thank you! With this libraries versions all work fine.
