### ISSUE TITLE
The loaded model behaves inconsistently

### ISSUE THREAD

**Issue by bessszilard** [divamgupta/image-segmentation-keras#178]
First of all, thank you for this awesome library!

I exported, and imported the model with this code:
```python
# save weights
model.save_weights("model.h5")
```

```python
from keras_segmentation.models.unet import vgg_unet

# load model
model_weight_path = 'model.h5'
model = vgg_unet(n_classes=6,  input_height=640, input_width=640)
model.load_weights(model_weight_path, by_name=True)
```

In some cases when I load the model, I got good prediction results that is middle in the table, and then if I use the same code, the same model, I got this strange result which is bottom in the table.

I use 
Google Colab,
Keras 2.1.0.
keras-segmentation-0.2.0

I installed keras-segmentation with pip. I tried with Keras 2.2.5 as well, and I got the same strange behavior.

What can it cause this phenomenon?

Thanks, for your help!

|  Original image    |  ![top_potsdam_2_10_RGB](https://user-images.githubusercontent.com/48211034/76547225-c0b88400-6484-11ea-8620-39cd9d82837b.jpg) |
| ---- | ---- |
|  Good result    |    ![top_potsdam_2_10_RGB_proc](https://user-images.githubusercontent.com/48211034/76547042-70412680-6484-11ea-9e51-d3f59efd12f6.png) |
|  Bad result    |  ![top_potsdam_2_10_RGB_proc](https://user-images.githubusercontent.com/48211034/76546931-3c660100-6484-11ea-9f4d-467d07c8843c.jpg)    |

**Comment by divamgupta** [comment]
That is strange. Could you share some reproducible snippet or the maybe the collab notebook? I can take a look.

**Comment by bessszilard** [comment]
https://colab.research.google.com/drive/1l0O8PUpS_qwWn_TXROi1p3EWG9tTKfpL

**Comment by bessszilard** [comment]
@divamgupta how can I compare the weights?
The problem is at the export or at the import side?

**Comment by divamgupta** [comment]
@bessszilard , replace `model.load_weights(model_weight_path, by_name=True)` with `model.load_weights(model_weight_path)` and it should work fine!

**Comment by bessszilard** [comment]
Yes, this solved my issue. Thank you @divamgupta!
