### ISSUE TITLE
Does it make a difference how we scale the labeled images to be used in image segmentation?

### ISSUE THREAD

**Issue by Philliec459** [divamgupta/image-segmentation-keras#181]
Does it make a difference is scaling the labeled images from 1 to max number of segments or scale the images from 0 to 255 where each segment has a unique value within this range? I have created a repository showing how we are labeling Thin Section images:

https://github.com/Philliec459/Create-Thin-Section-Image-Labels-for-Image-Segmentation-Training

I have been using the 1 to max number of segments to create the labeled images for annotated images, but do the label scales make a difference?

![Interactive](https://user-images.githubusercontent.com/56929340/76903899-7b210000-6864-11ea-8512-b92db18237d7.png)

**Comment by divamgupta** [comment]
Yes, my code to read the segmentation labels only considers pixels of values 0 to n_classes.

**Comment by Philliec459** [comment]
Great. Thank you. I will adjust my code accordingly.
