### ISSUE TITLE
Robust semantic segmentation algorithm 

### ISSUE THREAD

**Issue by bessszilard** [divamgupta/image-segmentation-keras#182]
I am trying to do segmentation on satellite images. For the test image1 the neural network performs well, but on image2, not. Both are test images, so I didn't use them for training. I thought that if I use augmentation, I can get a more robust neural network. I used the do_augment=True flag, and a result improved a little bit, but not sufficiently. I got similar results on vgg_unet, resnet50_unet and resnet50_segnet.

Does it help if I do some preprocessing on image 2?
What can I do to have a more robust result? 

| image1 | ![Selection_010](https://user-images.githubusercontent.com/48211034/77101482-a8fa7600-6a17-11ea-816a-ee5f1bce0405.png)  |
| --- | --- |
| **image2** | ![image](https://user-images.githubusercontent.com/48211034/77101518-bf083680-6a17-11ea-8bfb-6c38c456e035.png) |

Thanks for your help!

Regards,
Szilard

**Comment by divamgupta** [comment]
You can try fine-tuning from a pre-trained model.

**Comment by bessszilard** [comment]
Thank you @divamgupta, that solved my problem!
