### ISSUE TITLE
AssertionError about png file

### ISSUE THREAD

**Issue by coco401** [divamgupta/image-segmentation-keras#185]
Im sure I have dataset1 and both images are in .png .
Here is a error:
from_paths
    assert ( seg in segmentations_d ),  (im + " is present in "+images_path +" but "+seg_bnme+" is not found in "+segs_path + " . Make sure annotation image are in .png"  )
AssertionError: dataset1/images_prepped_train\0001TP_006690.png is present in dataset1/images_prepped_train/ but 0001TP_006690.png is not found in dataset1/annotations_prepped_train/ . Make sure annotation image are in .png
(base)

**Comment by divamgupta** [comment]
Hi,

Are you facing this issue if you install the master version of the library?

`pip install --upgrade git+https://github.com/divamgupta/image-segmentation-keras`

**Comment by divamgupta** [comment]
Closing this as this error would not occur in the latest version.
