### ISSUE TITLE
what is the What's the meaning of 'cl_wise_score = tp / ( tp + fp + fn + 0.000000000001 )'

### ISSUE THREAD

**Issue by winynfuck** [divamgupta/image-segmentation-keras#187]
Does this word cl_wise_score mean the accuracy of each category？Besides,
I don't quite understand why 0.000000000001  is added here.
I really need you to help me out

**Comment by divamgupta** [comment]
This is to prevent 0/0 division error.

**Comment by winynfuck** [comment]
On, thanks

**Comment by inesbouhajeb** [comment]
What exactly mean evaluate method outpus values? Can you describe "frequency_weighted_IU", "mean_IU" and "class_wise_IU"? The last one is non of these: [link](https://www.semanticscholar.org/paper/Reducing-False-Positive-in-Intrusion-Detection-%3A-A-Gupta-Srivastava/4a2c0b466170af931e75ef5a0f03805807cebf2e/figure/1) How to get accuracy?
