### ISSUE TITLE
Segfault in predict.py

### ISSUE THREAD

**Issue by neuvo** [divamgupta/image-segmentation-keras#19]
Seemingly at the very end of running predict.py, the program segfaults. It occurs after the for loop that iterates through all the images. It seems that everything works, so it's unclear where the segfault is happening or if it's even actually a problem.

**Comment by divamgupta** [comment]
What version of keras, backend, cuda, cudnn are you using?

**Comment by neuvo** [comment]
Keras 2.1.4
Backend: Theano 1.0.1
My computer does not have a GPU so I do not believe any cuda or cudnn code is running.

**Comment by divamgupta** [comment]
Image segmentation keras has been updated with tensorflow support. It should fix the issue.
