### ISSUE TITLE
Dataset creation

### ISSUE THREAD

**Issue by Cipherpy** [divamgupta/image-segmentation-keras#193]
Sir, how did you create the dataset? which annotation software and how did you create the masks from annotation

**Comment by simenkf** [comment]
I cannot speak for the author of this repo, but I have had great success with Labelbox. Its free up until (I think) 1 000 images and easy to use. LabelMe is another popular choice.

**Comment by Cipherpy** [comment]
Thank you sir for the reply. I have created annotated images for Mask RCNN using VIA. What modification I should make for creating a dataset for Unet

**Comment by simenkf** [comment]
You need your images in one folder and masks in a separate folder. Corresponding files should have the same file name. Also, segmentation masks must have pixel values corresponding to class IDs (e.g. only zeros and ones for binary segmentation). What format is your data currently in? I do not know VIA.

**Comment by Cipherpy** [comment]
Currently my annotations are in this form

[{
    "filename": "000dfce9-f14c-4a25-89b6-226316f557f3.jpeg",
    "regions": {
        "0": {
            "region_attributes": {
                "object_name": "Cat"
            },
            "shape_attributesa": {
                "all_points_x": [75.30864197530865, 80.0925925925926, 80.0925925925926, 75.30864197530865],
                "all_points_y": [11.672189112257607, 11.672189112257607, 17.72093488703078, 17.72093488703078],
                "name": "polygon"
            }
        },
        "1": {
            "region_attributes": {
                "object_name": "dog"
            },
            "shape_attributes": {
                "all_points_x": [80.40123456790124, 84.64506172839506, 84.64506172839506, 80.40123456790124],
                "all_points_y": [8.114103362391036, 8.114103362391036, 12.205901974737595, 12.205901974737595],
                "name": "polygon"
            }
        }
    },
    "width": 504,
    "height": 495
}] have multiple object classes in an image. The shape_attributes contains the annotations of the object. Is the same format suitable for unet?

**Comment by simenkf** [comment]
I'm afraid you'll have to convert that into segmentation masks as png-files. There are probably scripts for that online. I suggest you look around or write one yourself. I have used LabelBox which automatically generate such png files for me.

**Comment by Cipherpy** [comment]
> I'm afraid you'll have to convert that into segmentation masks as png-files. There are probably scripts for that online. I suggest you look around or write one yourself. I have used LabelBox which automatically generate such png files for me.

Thank you for your help. I will definitely try in that way

**Comment by Cipherpy** [comment]
Do we need binary masks corresponds to each unique category? I mean corresponds to each individual training image there will be a folder of images each contains binary mask correspond to each object class. one class versus background. likewise for each unique object.
