### ISSUE TITLE
The problem of input size

### ISSUE THREAD

**Issue by lyc1995452-star** [divamgupta/image-segmentation-keras#194]
File "E:\Anaconda\envs\keras\lib\site-packages\keras_segmentation\train.py", line 81, in train
    n_classes, input_height=input_height, input_width=input_width)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras_segmentation\models\unet.py", line 122, in vgg_unet
    input_height=input_height, input_width=input_width)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras_segmentation\models\unet.py", line 73, in _unet
    input_height=input_height, input_width=input_width)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras_segmentation\models\vgg16.py", line 19, in get_vgg_encoder
    assert input_height % 32 == 0

**Comment by divamgupta** [comment]
Hi, the input height and width should be multiple of 32.

**Comment by lyc1995452-star** [comment]
Thanks you reply!My data size is fixed, the hight 420, width 560, What should I do?

**Comment by divamgupta** [comment]
The code will automatically resize the data to the model size while training.

**Comment by lyc1995452-star** [comment]
image-segmentation-keras-master\keras_segmentation\models\unet.py", line 122, in vgg_unet
    input_height=input_height, input_width=input_width)
image-segmentation-keras-master\keras_segmentation\models\unet.py", line 73, in _unet
    input_height=input_height, input_width=input_width)
image-segmentation-keras-master\keras_segmentation\models\vgg16.py", line 19, in get_vgg_encoder
    assert input_height % 32 == 0
AssertionError
But,  My problem is not solved

**Comment by monicaglez** [comment]
I have the same problem. Did you solve it?
