### ISSUE TITLE
Training is too fast

### ISSUE THREAD

**Issue by furkan59** [divamgupta/image-segmentation-keras#195]
I think my model trains too fast. 

Because training 89000 images with 5 encode layer takes 10 minutes to train for 1 epoch. 
My images 512x512 images

Is it normal ? 
my code is like that 

`
def train():
    model = vgg_unet(n_classes=2 ,  input_height=512, input_width=512,encoder_level = 5)
    
    model.train(
        train_images =  inputDir,
        train_annotations = outputDir,
        checkpoints_path = checkPoints , epochs=20)

if __name__ == '__main__': 
    train()

`

**Comment by furkan59** [comment]
![image](https://user-images.githubusercontent.com/7033465/79310552-d3e7c500-7f04-11ea-8ef7-ce0dbbdd36df.png)

it is like that

**Comment by divamgupta** [comment]
Actually here epoch is only for 512 mini batches, not the complete dataset. You can change steps_per_epoch if you want more mini-batches per epoch.

**Comment by furkan59** [comment]
Thanks.
