### ISSUE TITLE
Person segmentation

### ISSUE THREAD

**Issue by furkan59** [divamgupta/image-segmentation-keras#196]
Hi,

I want o segment person from background. What is the proposed model for this task. 

I want to make something like this as output. I have only 2 classes. 

- Person 
- Not person(background)

Input image will be same size as output image. I want tı segment 512x512 images. 

result will be single channel 512x512 image with black and white 

black = 0,0,0
white = 255,255,255

![image](https://user-images.githubusercontent.com/7033465/79441991-98bac400-7fe0-11ea-9e9e-a1ee150c1b8a.png)

I have tried pspnet_101_voc12 pretrained model 

results are like this. I threshold images manually.

![image](https://user-images.githubusercontent.com/7033465/79442251-f7803d80-7fe0-11ea-803c-037896fda429.png)

for the same images with vgg-unet 
I trained the vgg-unet model my self with nearly 90000 images. For 15 hours
result are like this

![image](https://user-images.githubusercontent.com/7033465/79442311-11218500-7fe1-11ea-88bf-fc8c5a6b537c.png)

**Comment by divamgupta** [comment]
Try fine-tuning a pre-trained model. Maybe data augmentation might help in your case. Changing the input image size could also help.

**Comment by furkan59** [comment]
For data augmentation I flip the images horizontally. It helped. Thanks.
