### ISSUE TITLE
The pixel values of the segmentation image data/double_label/11757997.png violating range [0, 6]. Found maximum pixel value 7

### ISSUE THREAD

**Issue by luluwang0** [divamgupta/image-segmentation-keras#199]
I set the n_classes=7, but not every image in the training data contains 7 categories. it causes the AssertionError
what should i do?

**Comment by divamgupta** [comment]
If n_classes=7 , then the annotation files should not have any value>=7 .
Please make sure the annotation files are processed correctly.
