### ISSUE TITLE
Found error during data loading

### ISSUE THREAD

**Issue by andrew21111** [divamgupta/image-segmentation-keras#204]
I created two folders, the first one with the original and the second one with the mask.
The name format is img_ID.jpg.

I double checked image per image, and name are all the same, but I get always the same error:

No corresponding segmentation found for image

**Comment by divamgupta** [comment]
You have to use .png for the segmentation masks

**Comment by andrew21111** [comment]
Yeah I already resolved. I forgot to mark it as resolved! However, thank you !
