### ISSUE TITLE
conda not found when running docker file

### ISSUE THREAD

**Issue by temi92** [divamgupta/image-segmentation-keras#209]
Hi i am trying to build a docker image using your docker file however i get an error 
/bin/sh  miniconda/bin/conda not found 
Could you please provide any tips on resolving this.

**Comment by divamgupta** [comment]
@JaledMC

**Comment by JaledMC** [comment]
Hi,

I'm glad this docker can be useful. Yes, I encounter the same problem, maybe because a new conda version, with different path. Problem is solved, but before the pull request, I have to point the conda to an specific version, instead the latest, to prevent future crashed. Give me a moment

**Comment by JaledMC** [comment]
@temi92 , This pull request probably solves your issue. It works for me. Can you give a try?

I added fixed versions for tf, keras and conda, to prevent future mismatches (pointing to latest is "code smell" in docker)
