### ISSUE TITLE
Returning undefined variable 

### ISSUE THREAD

**Issue by mzahana** [divamgupta/image-segmentation-keras#212]
In (https://github.com/divamgupta/image-segmentation-keras/blob/master/keras_segmentation/predict.py#L166) there is 
`return pr`, but `pr` does not exist.
Did you mean `return seg_img`?

**Comment by divamgupta** [comment]
`pr` does exist. `seg_img` is the final colored image for visualisation of the segmentation. `pr` is a numpy array containing the predicting  class IDs of each pixel.
