### ISSUE TITLE
Work with grayscale images (1 channel)

### ISSUE THREAD

**Issue by A4Ayou** [divamgupta/image-segmentation-keras#213]
Hi,

Is there possibility to work with input images which are on **gray scale** (with just **one channel** instead of the RGB ones)?
If yes, how to proceed?

I tried to change the input layer, but model was then returning an error since regarding format of the inputs. 

Thanks!

**Comment by divamgupta** [comment]
I think both the data loading function and the model has to be changed. 
One trick you can do is to convert the gray scale image to RGB by repeating the content in 3 channels. That should give similar performance.

**Comment by A4Ayou** [comment]
Thanks !
