### ISSUE TITLE
None -- [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by AlbertPYB** [divamgupta/image-segmentation-keras#215]
when  I run the example, the error as follow:
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5:

What shold I do?? Thank you very much

**Comment by MrLuer** [comment]
我也遇到同样的问题，请问怎么解决的
