### ISSUE TITLE
Expected segmentation speed using GPU

### ISSUE THREAD

**Issue by mzahana** [divamgupta/image-segmentation-keras#218]
Hi @divamgupta ,

I would like to get a sense of segmentation speed when using GPU. I have GeForce GTX 1050 Ti and I am running this package inside a docker container to keep it isolated from my system. I am using Cuda10.1 + TensorFlow 2.0.0, and I am getting segmentation in a rate of ~ 0.6sec/image by executing [pspnet_50_ADE_20K](https://github.com/divamgupta/image-segmentation-keras#pre-trained-models) on series of images, by timing the execution of 
```python
out = model.predict_segmentation(
    inp="input_image.jpg",
    out_fname="out.png"
)
```

Is this a normal speed? or it can be faster?

**Comment by divamgupta** [comment]
Yes, I think that is the expected speed.
