### ISSUE TITLE
Show the only the outline of the segmented surface

### ISSUE THREAD

**Issue by bessszilard** [divamgupta/image-segmentation-keras#222]
What is an efficient way to show only the outline of the segmented surface?
Instead of getting an image a to get image b.
I can't do edge detection because I will lose the class id information in the segmented image

| ![Selection_283](https://user-images.githubusercontent.com/48211034/85005753-82082900-b159-11ea-9c68-2e00ae038c8b.jpg)  | ![Selection_284](https://user-images.githubusercontent.com/48211034/85005747-803e6580-b159-11ea-81bc-ae9e395cdeee.jpg)     |
|  :-: |  :-: |
| a)     |   b)   |

Thanks for the help!

**Comment by divamgupta** [comment]
One option is to do edge detection on each class separately, rather than doing it on the whole segmented image.

**Comment by bessszilard** [comment]
The solution pseudo code is:
```
kernel = [5, 5]
out = segmentation(original_image)
out_edges = canny(out)
out_edges = dilate(out_edges, kernel) # increase edge width
out_edges_only = bitwise_and(out_edges, out)
```
