### ISSUE TITLE
Resnet50_unet trained on ADE20K is not working

### ISSUE THREAD

**Issue by TrachIvan** [divamgupta/image-segmentation-keras#231]
Hi,

I have trained Resnet50_unet and several other models on ADE20K dataset, and all model produce very purely, am I missing something? I have just downloaded dataset and tried is it working, should I do any preprocessing before train?

Here used training command:
python -m keras_segmentation train  --checkpoints_path="/tmp/resnet50_unet"  --train_images="images/training/"  --train_annotations="annotations/training/"  --val_images="images/validation/"  --val_annotations="annotations/validation/"  --n_classes=158  --input_height=320  --input_width=640 --model_name="resnet50_unet" --epochs=32

And code for test:
from keras_segmentation.pretrained import pspnet_50_ADE_20K , pspnet_101_cityscapes, pspnet_101_voc12
from keras_segmentation.models.unet import vgg_unet,resnet50_unet
from keras_segmentation.models.segnet import resnet50_segnet
from keras_segmentation.models.pspnet import pspnet

model = resnet50_unet(n_classes=58 ,  input_height=320, input_width=640) 
#model = pspnet_101_voc12()

out = model.predict_segmentation(
    inp="in.jpeg",
    out_fname="out1.png",
    checkpoints_path = "/tmp/resnet50_unet"
)

I have tried different number of classes, models and datasets, and seems it is not going to work. Does any body can help?
![out1](https://user-images.githubusercontent.com/43246373/90249836-db33c680-de43-11ea-804a-a1f18719459e.png)
![in1](https://user-images.githubusercontent.com/43246373/90249873-e686f200-de43-11ea-8c39-57a9d9b485f5.jpeg)

Best Regards, Ivan

**Comment by TrachIvan** [comment]
Hi,

Trained on sample dataset provided in README and still have very bad results, is this project still supported? Cant explain such bad results on custom dataset
![out24](https://user-images.githubusercontent.com/43246373/90425810-0844db00-e0c9-11ea-9c5c-26c3179fd483.png)

Train cmd:
python -m keras_segmentation train  --checkpoints_path="/tmp/vgg_unet_1"  --train_images="dataset1/images_prepped_train/"  --train_annotations="dataset1/annotations_prepped_train/"  --val_images="dataset1/images_prepped_test/"  --val_annotations="dataset1/annotations_prepped_test/"  --n_classes=50  --input_height=320  --input_width=640  --model_name="vgg_unet"

Test command:
python -m keras_segmentation predict  --checkpoints_path="/tmp/vgg_unet_1"  --input_path="dataset1/images_prepped_test/0016E5_07959.png"  --output_path="./out24.png"

Best Regards, Ivan

**Comment by divamgupta** [comment]
Hi,
Which keras/tf versions are you using. The example should work for tensorflow-gpu==1.4.0 and  keras==2.1.3 .
I will look into testing with the newer versions as well.

**Comment by divamgupta** [comment]
It's fixed now. Everything should work with latest TF/keras versions.
Here is a working google colab example: https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing
