### ISSUE TITLE
Prediction on arrays?

### ISSUE THREAD

**Issue by GGDRriedel** [divamgupta/image-segmentation-keras#234]
I am trying to predict a few thousand images that are basically sections of a really really long data array. 

Ideally I would do it like so: 
```
temp = np.empty((237,0))
for j in tqdm.tqdm(range(int(testdata.traces.shape[0]/250))):
    data=testdata.traces[250*j:250*(j+1),:].T
    
    data=((data-data.min())/(data.max()-data.min()))*255
    #stacking because library wants (m,n,3):
    stackdata= np.repeat(data[:, :, np.newaxis], 3, axis=2)

    yo=model.predict_segmentation(
    inp=stackdata)
    temp = np.append(temp, yo, axis=1)
```

This doesn't work. 
Numerically, the prediction is absolute crap. 

So basically I need documentation on what format the input array needs to be. 
The model was trained on ~1500 grayscale images. 
I do not know waht the input needs to look like and what data range needs to be in it. 
Grayscale mapped to 3 array channels? 

cheers

**Comment by GGDRriedel** [comment]
The png image for training is a grayscale image written with cv2. 
It is derived from GPR(Ground penetrating Radar) data. Basically a 250(y) x 100k(x) array chopped into image seized pictures of 250x250. 
These are written as pngs for training and training works god. 

Now I need to classify another one. 
I basically already have a  np.array. 

The function you pointed out would not work for that as it seems to contain this line: 

```
if type(image_input) is np.ndarray:
        # It is already an array, use it as it is
        img = image_input
```

**Comment by GGDRriedel** [comment]
I still haven't solved this as the process the model uses to classify an array seems to be different to the process when it reads an image?


Why do I get a different result, even though the array I read in from a written image file is numerically the same as the one I am giving it as an array?

**Comment by divamgupta** [comment]
One way to debug this is to modify the library code and printing / saving the input just before model.predict
