### ISSUE TITLE
Software image segmentation

### ISSUE THREAD

**Issue by Caioww** [divamgupta/image-segmentation-keras#238]
What software was used to segment the sample dataset?

**Comment by thezaza101** [comment]
Definitely not an official answer, but i've used the following process for this project: https://github.com/thezaza101/Meal-Compliance-Project
The project uses the UNET code from this package.

Creating ground truth images: https://www.youtube.com/watch?v=7GtePHvsTGQ
Creating labeled images: https://github.com/thezaza101/Meal-Compliance-Project/blob/master/SegmentMapMerger/SegmentMapMerger.ipynb

**Comment by divamgupta** [comment]
You can use labelme also
