### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [divamgupta/image-segmentation-keras#24]
I get AssertionError for line 61 in LoadBatches.py that is, for the following line:

assert images_path[-1] == '/'

What could be the problem? In fact, I get AssertionError in all files whereever assert [-1] is present

**Comment by divamgupta** [comment]
You must not be ending the directory name with a forward slash.  See the example in the readme.

**Comment by Saumya-Gupta-26** [comment]
Worked perfectly, thank you!
