### ISSUE TITLE
Checkpoint Issues 

### ISSUE THREAD

**Issue by beauhobba** [divamgupta/image-segmentation-keras#240]
The following error is happening every time I try to read from checkpoints previously learnt.  I was hoping there is a temporary fix or anything. I have tried downgrading to Keras 2.0 and tensorflow 1.4, but I still have the same problem. Is there any other way to save the weights, or to read the checkpoints. 

`  predict( 
    checkpoints_path="/content/drive/My Drive/Semantic/SEMANTIC/SemanticSegment/checkpoints/vgg", 
    inp="/content/drive/My Drive/Semantic/SEMANTIC/SemanticSegment/verification/3738.png", 
    out_fname="out.png" 
  )`

The error message: 

`AssertionError                            Traceback (most recent call last)
<ipython-input-11-de4784a8cea3> in <module>()
     12     checkpoints_path="/content/drive/My Drive/Semantic/SEMANTIC/SemanticSegment/checkpoints/vgg",
     13     inp="/content/drive/My Drive/Semantic/SEMANTIC/SemanticSegment/verification/3738.png",
---> 14     out_fname="out.png"
     15   )

1 frames
/usr/local/lib/python3.6/dist-packages/keras_segmentation/predict.py in model_from_checkpoint_path(checkpoints_path)
     22     from .models.all_models import model_from_name
     23     assert (os.path.isfile(checkpoints_path+"_config.json")
---> 24             ), "Checkpoint not found."
     25     model_config = json.loads(
     26         open(checkpoints_path+"_config.json", "r").read())

AssertionError: Checkpoint not found.`

I

**Comment by divamgupta** [comment]
Hi, this have been fixed now. 
You can uninstall the existing keras_segmentation and install the master branch using : `pip install git+https://github.com/divamgupta/image-segmentation-keras
`
That should solve the error.
