### ISSUE TITLE
Data Prep

### ISSUE THREAD

**Issue by mavaylon1** [divamgupta/image-segmentation-keras#254]
Hi I'm trying to use the publicly available oxford pet dataset which has three classes. The masks are trimaps, can you give advice on how we would need to prep the images? 

Should I convert the trimap into 3-channel one hot encoded version?

**Comment by divamgupta** [comment]
As mentioned in the readme and the blogpost, you should fill the image with integers values at each pixel denoting the class. Eg. '0' for background , '1' for foreground , etc.

**Comment by mavaylon1** [comment]
I read what you wrote and my question still stands.
