### ISSUE TITLE
Predict_multiple fails silently

### ISSUE THREAD

**Issue by awilliamson** [divamgupta/image-segmentation-keras#264]
When using predict_multiple, if the out_dir doesn't exist, the program will execute and still predict supplying the user with a progress bar, however the frames will not be stored anywhere.

I ended up creating the folder midway through, then frames could save out. It looks like any error for lack of the target dir not existing is squashed.

**Comment by divamgupta** [comment]
Hi,

This has been fixed, the fix is currently in the dev branch and will be merged into the master branch soon.
