### ISSUE TITLE
Preparing the data for training

### ISSUE THREAD

**Issue by dehai-bai** [divamgupta/image-segmentation-keras#278]
```
import cv2
import numpy as np

ann_img = np.zeros((30,30,3)).astype('uint8')
ann_img[ 3 , 4 ] = 1 # this would set the label of pixel 3,4 as 1

cv2.imwrite( "ann_1.png" ,ann_img )
```

What is the meaning of this code? I run directly under the folder to get an "ann_1.png" file.
And then
How to annotate a whole folder of pictures. Still copy these N copies and change them to the name of the corresponding picture. Because I didn’t see that the generated picture was generated based on that picture.
Thanks! I am limited.

**Comment by hosseinshirali** [comment]
This is just a simple example to show how to annotate a pixel in an image.
To annotate your pictures I suggest you use  [```labelme```](https://github.com/wkentaro/labelme).
