### ISSUE TITLE
Memory Allocation Issue

### ISSUE THREAD

**Issue by aashirwadpatel703** [divamgupta/image-segmentation-keras#279]
I am trying to train a fcn_32_resnet50 model. I run the following:

from keras_segmentation.models.fcn import fcn_32_resnet50
model = fcn_32_resnet50(n_classes=34 ,  input_height=416, input_width=608  )

And I get "ResourceExhaustedError: OOM when allocating tensor"

So far I have trained vgg_unet, fcn_32_vgg and resnet50_pspnet and they worked fine on Cityscape dataset (around 23k images in total).  
I also tried reinstalling TF, with and without TF-GPU (normally others work fine without tf-gpu installed). 

My GPU is Nvidia RTX2060 (6gb memory)
I tried it on TF2.4.1 with CUDA11 and also TF2.2.0 with CUDA10.2 and getting the same error both the times.

**Comment by divamgupta** [comment]
Well, you are getting out of memory error. You need a gpu with larger memory or try reducing the input size.
