### ISSUE TITLE
Why is the annotation picture completely black when opened

### ISSUE THREAD

**Issue by dehai-bai** [divamgupta/image-segmentation-keras#281]
![0016E5_07959](https://user-images.githubusercontent.com/65593855/111429992-b59dd100-8734-11eb-8d7c-a60d58b632c5.png)

**Comment by divamgupta** [comment]
This is probably because there would be fewer number or classes. If you
read the pixel values of the annotation image, you should see the class Ids

**Comment by dehai-bai** [comment]
Thank you for your reply. 
In the data set "dataset1" you provided, the annotation pictures are also completely black.

I don’t know how to use the example code you provided to generate annotated images。 I created four folders.
As the picture shows:
![屏幕截图 2021-03-20 114704](https://user-images.githubusercontent.com/65593855/111858219-47465200-8972-11eb-9253-6b51fffe67be.png)
I put the training and test data sets into the two folders, and how can I use this code to generate annotation files in the appropriate folder.

This is what you provide：
`import cv2
import numpy as np

ann_img = np.zeros((30,30,3)).astype('uint8')
ann_img[ 3 , 4 ] = 1 # this would set the label of pixel 3,4 as 1

cv2.imwrite( "ann_1.png" ,ann_img )`
If I can receive your reply, it will be my honor.
