### ISSUE TITLE
AssertionError: Checkpoint not found.     analogous to #237 issue

### ISSUE THREAD

**Issue by DomenicoMessina** [divamgupta/image-segmentation-keras#286]
Hi,

I've encountered the same issue of #237. 
I tried to run this google colab notebook, without positive results

https://colab.research.google.com/drive/1Kpy4QGFZ2ZHm69mPfkmLSUes8kj6Bjyi?usp=sharing#scrollTo=79ib1d3xFpAy

You developed a fantastic library. I hope you will fix this issue.
Thanks,
Domenico

**Comment by divamgupta** [comment]
I just ran colab this notebook. And it works perfectly fine and I am not able to reproduce the error you are facing.

**Comment by DomenicoMessina** [comment]
Thank you for your fast answer, Divamgupta.

I've added to the notebook the module google.colab to have the access to drive, using the following code 

import os
from google.colab import drive
drive.mount('/gdrive/',force_remount = True)

os.symlink('/gdrive/My Drive/', 'my_drive')


After that, I manually downloaded and extracted your dataset in a subfolder of my_drive folder. Maybe the code do not recognize this?

**Comment by PaulaScharf** [comment]
I also have the same error. It runs fine when I run the google colab but if I try the same commands on my home PC it cant find the checkpoints. Specifically this [line](https://github.com/divamgupta/image-segmentation-keras/blob/52ec91e1625d67a79126d8cf9a287d64d03f4e9f/keras_segmentation/train.py#L21) does not seem to find any files in my checkpoints-folder.

**Comment by divamgupta** [comment]
Which OS are you using and what is exact command you are using?

**Comment by PaulaScharf** [comment]
I am on Windows 10 home (x64). 
I downloaded the datasets with the given [link](https://drive.google.com/file/d/0B0d9ZiqAgFkiOHR1NTJhWVJMNEU/view?usp=sharing). 
Then I ran 
`python -m keras_segmentation train --checkpoints_path="/tmp/vgg_unet_1" --train_images="dataset1/images_prepped_train/" --train_annotations="dataset1/annotations_prepped_train/" --val_images="dataset1/images_prepped_test/" --val_annotations="dataset1/annotations_prepped_test/" --n_classes=50 --input_height=320 --input_width=640 --model_name="vgg_unet" --epochs=5` 
and then 
`python -m keras_segmentation predict --checkpoints_path="/tmp/vgg_unet_1" --input_path="dataset1/images_prepped_test/0016E5_07959.png" --output_path="./out24.png"`. 
Then I get the same error as in #237.

It works if I change [this line](https://github.com/divamgupta/image-segmentation-keras/blob/52ec91e1625d67a79126d8cf9a287d64d03f4e9f/keras_segmentation/train.py#L21) to the following:
`all_checkpoint_files = glob.glob(checkpoints_path + "*.*")`

**Comment by divamgupta** [comment]
Thanks. This package has not been tested with windows. How does the
checkpoints directory look like? I was trying to understand why it
currently fails.

**Comment by PaulaScharf** [comment]
![Screenshot 2021-03-31 143852](https://user-images.githubusercontent.com/48286621/113145571-dc78fe80-922e-11eb-9a4c-7b0fc5388e10.jpg)

(I aborted training after 1 epoch because it takes so long)

**Comment by divamgupta** [comment]
Thanks, I have fixed it in the latest commit.
