### ISSUE TITLE
Hello, the author provides the dataset dataset1, comment diagram open is all black, this is what kind of dataset, if I want to train VOC2012, how to change

### ISSUE THREAD

**Issue by dehai-bai** [divamgupta/image-segmentation-keras#289]

**Comment by divamgupta** [comment]
Hi,

The dataset1 is not all black. Looking it the pixel values of the annotation images, you should be able to see the class IDs. 

Using this command you should be able to visualize the dataset:
```
python -m keras_segmentation visualize_dataset \
 --images_path="dataset1/images_prepped_train/" \
 --segs_path="dataset1/annotations_prepped_train/"  \
 --n_classes=50
```

**Comment by dehai-bai** [comment]
Thank you. 
How to train VOC2012?

**Comment by divamgupta** [comment]
You would need to create a annotation images where each at location the pixel value should be equal to the class ID. You can refer to the blog post for more information.
