### ISSUE TITLE
the dimension?

### ISSUE THREAD

**Issue by lsymuyu** [divamgupta/image-segmentation-keras#29]
https://github.com/divamgupta/image-segmentation-keras/blob/3894259e2711be669557c9ee940c338b38cbd8ec/LoadBatches.py#L54

Is it should be seg_labels = np.reshape(seg_labels, ( width, height , nClasses ))?

Thanks.

Shouyang

**Comment by divamgupta** [comment]
At prediction time we reshape it back to our original dimensions. So this is correct.
