### ISSUE TITLE
Fit doesn't work on gpu 

### ISSUE THREAD

**Issue by mavaylon1** [divamgupta/image-segmentation-keras#290]
When running on gpu I get
ValueError: `y` argument is not supported when data isa generator or Sequence instance. Instead pass targets as the second element of the generator.

But it works when on cpu

Traceback (most recent call last):
  File "ResNet_Vanilla_3_class-Updated.py", line 348, in <module>
    val_steps_per_epoch=len(glob("/home/maavaylon/Data1/test/img/*"))
  File "/home/maavaylon/LBNL_Seg/LBNL_Segmentation_crf/image_segmentation_keras/keras_segmentation/train.py", line 187, in train
    use_multiprocessing=gen_use_multiprocessing)
  File "/home/maavaylon/anaconda3/envs/fit/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1064, in fit
    steps_per_execution=self._steps_per_execution)
  File "/home/maavaylon/anaconda3/envs/fit/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1112, in __init__
    model=model)
  File "/home/maavaylon/anaconda3/envs/fit/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 769, in __init__
    raise ValueError("`y` argument is not supported when using "
ValueError: `y` argument is not supported when using python generator as input.

**Comment by divamgupta** [comment]
Which keras / tensorflow version are you using? And what are the commands to reproduce this error. Because it works fine on the google colab example on both CPU and GPU.

**Comment by mavaylon1** [comment]
Python 3.7.10
Keras 2.4.3 (using keras-gpu)
Tensorflow 2.4.1

I'm running the resnet50 unet. Its been a while since I git pulled, I've been using the gpu with fit_generator. I saw that you guys updated to fit back in January so I git pulled. I tried training the resnet via:

model.train(
    train_images =  "/Users/mavaylon/Research/Data1/train/img/",
    train_annotations = "/Users/mavaylon/Research/Data1/train/ann/",
    epochs=20,
    steps_per_epoch=len(glob("/Users/mavaylon/Research/Data1/train/img/*")),
    batch_size=1,
    validate=True,
    val_images="/Users/mavaylon/Research/Data1/test/img/",
    val_annotations="/Users/mavaylon/Research/Data1/test/ann/",
    val_batch_size=1,
    val_steps_per_epoch=len(glob("/Users/mavaylon/Research/Data1/test/img/*"))
)

This is after using get_segmentation_model to compile the resnet and such. I tried running it and that error popped up, but when I go into train.py ans switch fit back to fit_generator then it works.

**Comment by ma-research** [comment]
Hello. This is also mavaylon1. What I ended up doing was creating a new fork on this new account and it works. Thanks for the great work!
