### ISSUE TITLE
vgg.load_weights(VGG_Weights_path) Error: input shapes: [102400,4096], [25088,4096] 

### ISSUE THREAD

**Issue by VeniVidiGavi** [divamgupta/image-segmentation-keras#3]
I am getting an error at the line:
vgg.load_weights(VGG_Weights_path)

the error is:
ValueError: Dimension 0 in both shapes must be equal, but are 102400 and 25088 for 'Assign_26' (op: 'Assign') with input shapes: [102400,4096], [25088,4096].

Please note that:
I am running Keras with the Tensorflow backend because, with the Theano backend, I am getting an error which causes Theano to run on the CPU rather thsan the GPU (and only on 1 Core of the CPU).
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, ....

**Comment by divamgupta** [comment]
Yes, This error is because of the Tensorflow backend. We don;t support tensorflow backend currently. Try installing latest version of nvcc and theano.

**Comment by anas-899** [comment]
@VeniVidiGavi did you discover how to solve it? .. I got the same error

**Comment by noamgal** [comment]
@anas-899  I just removed the arguments `input_width` and `input_height` for both `train.py` and `predict.py`

**Comment by DawnMe** [comment]
@noamgal It works well, thanks! I got another error after the fix AttributeError: 'itertools.cycle' object has no attribute 'next', but changes to next(zipped) at "/image-segmentation-keras/LoadBatches.py" and now it works.

**Comment by gpkc** [comment]
If you remove the input_width and input_height it will simply use the default size of 224x224 I believe.

**Comment by quelibrio** [comment]
Yes default values don't work. Just go to /home/.keras/keras.json and change to
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "theano",
    "image_data_format": "channels_last"
}

**Comment by gpkc** [comment]
Then you'll be changing your backend to Theano. Some people can't use Theano (for example if you want to train on Google Cloud ML).

**Comment by quelibrio** [comment]
Ye you won't be able to train on google cloud, but since authors state "We don't support tensorflow backend currently" i don't see other option

**Comment by Cbanyungong** [comment]
This error happens because VGG16 was designed for images with size of 224. But the given code uses  Input(shape=(3,416,608). If you do not replace the input shape with (3,224,224),you will meet the error that "ValueError: Dimension 0 in both shapes must be equal, but are ***** and 25088 for 'Assign_26' (op: 'Assign') with input shapes: [****,4096], [25088,4096]".Remove arguments input_width and input_height for both train.py and predict.py and it worked well becasue the train.py and predict.py use default arguments" 224".I find the code don't support tensorflow backend because tensorflow uses "channels_last" and  theano uses "channels_first" .So if you want the code support tensorflow backend,just change input shape with (224,224,3) and change "data_format='channels_first'" with " data_format='channels_last". @VeniVidiGavi  @anas-899 @quelibrio @gpkc

**Comment by gpkc** [comment]
@Cbanyungong Why is it exactly that makes it necessary to keep the size 224? Aren't CNNs kernel-based and therefore independent of input size (i.e. they just train the kernel weights)?

**Comment by Ployl** [comment]
I'm getting this error in Line 105 of the FCN8 ( o = Add()([ o , o2 ])):
ValueError: Operands could not be broadcast together with shapes (14, 16, 10) (14, 14, 10)

Any ideas why this is happening?

I try to use tensorflow as backend aswell and did everything mentioned in this post.

**Comment by mgq1507** [comment]
> @noamgal It works well, thanks! I got another error after the fix AttributeError: 'itertools.cycle' object has no attribute 'next', but changes to next(zipped) at "/image-segmentation-keras/LoadBatches.py" and now it works.

Have you solved the problem?

**Comment by shodme** [comment]
@mgq1507  you can try to replace zipped.next() with zipped.__next__() in LoadBatches.py

**Comment by shodme** [comment]
@mgq1507 you can try to replace "zipped.next()" with "zipped.__next()__" in LoadBatches.py

**Comment by shodme** [comment]
@mgq1507 you can try to replace zipped.next() with zipped.\__next\__() in LoadBatches.py

**Comment by patrikoss** [comment]
@gpkc 
> Why is it exactly that makes it necessary to keep the size 224? Aren't CNNs kernel-based and therefore independent of input size (i.e. they just train the kernel weights)?

CNNs are indeed independent of input size, but VGG net is not fully convolutional. It has some fully-connected layers at the end. At the time of flattening the input the mismatch of the shape occur.

**Comment by divamgupta** [comment]
Image segmentation keras has been updated. The new version should fix the issue.
