### ISSUE TITLE
How to save and load the trained model

### ISSUE THREAD

**Issue by APatal** [divamgupta/image-segmentation-keras#345]
I am using :
`tf.keras.models.save_model(model,'my_model.hdf5')`
(also tried) `model.save()`
and then
`model=tf.keras.models.load_model('my_model.hdf5')`
and keep getting the error:
`AttributeError: 'Functional' object has no attribute 'predict_segmentation'`
when using
```
out = model.predict_segmentation(
    inp=image_to_test,
    out_fname="/tmp/out.png"
)
```

**Comment by momoai96** [comment]
Hey, 
sorry for the late answer. 
I did it by saving the model as json and the weights separately as h5. 
You can then load both and merge them together :)

**Comment by varungupta31** [comment]
Hey @momoai96,
I'm training on custom data, and I simply ran the [python script](https://github.com/divamgupta/image-segmentation-keras#:~:text=from%20keras_segmentation.models.unet,tmp/vgg_unet_1%22%20%2C%20epochs%3D5%0A) to train my model.

I get the output

```
Epoch 1/3
2022-04-14 23:45:31.284196: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2022-04-14 23:45:32.014281: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
 2/32 [>.............................] - ETA: 3s - loss: 0.0179 - accuracy: 0.5396WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0722s vs `on_train_batch_end` time: 0.1597s). Check your callbacks.
32/32 [==============================] - ETA: 0s - loss: 0.0193 - accuracy: 0.3511
Epoch 00001: saving model to logs/.00001
32/32 [==============================] - 24s 762ms/step - loss: 0.0193 - accuracy: 0.3511
Epoch 2/3
32/32 [==============================] - ETA: 0s - loss: 0.0099 - accuracy: 0.0387
Epoch 00002: saving model to logs/.00002
32/32 [==============================] - 23s 727ms/step - loss: 0.0099 - accuracy: 0.0387
Epoch 3/3
32/32 [==============================] - ETA: 0s - loss: 6.9894e-04 - accuracy: 0.0275
Epoch 00003: saving model to logs/.00003
32/32 [==============================] - 23s 730ms/step - loss: 6.9894e-04 - accuracy: 0.0275
```

However, the path I have for checkpoints contain no `.meta` `.index` files.
It only contains `checkpoint`  `_config.json` files, and checkpoint contains 
```
model_checkpoint_path: ".00003"
all_model_checkpoint_paths: ".00003"
```
Kindly help me out with how did you save the model.
Thanks

**Comment by momoai96** [comment]
Hey,

well, I'm not sure anymore. But I think I did it like this:

-create a directory for your model
-save weights only (model.save_weights('path_to_weights/weights')
-initialize a new model
-transfer the weights(model.load_weights('path_to_weights/weights')

hope that helps :))

**Comment by divamgupta** [comment]
![image](https://user-images.githubusercontent.com/1890549/170381898-fc2bb916-e963-43d5-a445-70bad347ea27.png)
