### ISSUE TITLE
train() got an unexpected keyword argument 'callbacks'

### ISSUE THREAD

**Issue by catpereira** [divamgupta/image-segmentation-keras#346]
I'm using the callbacks example on readme, however when I train, there's no parameter in train function regarding callbacks. When I changed the train function, I had another error : TypeError: image segmentation generator() got an unexpected keyword argument 'custom augmentation'. However this time the argument exists so I can't understand why this happens.

This is my code:
from keras_segmentation import train
model.train( 
    train_images =  "/content/drive/MyDrive/Datadim/train_images/",
    train_annotations = "/content/drive/MyDrive/Datadim/train_segmentation/",
    checkpoints_path = "/content/drive/MyDrive/Datadim" ,
    callbacks = callbacks, steps_per_epoch=5, epochs=2
)

**Comment by momoai96** [comment]
I think you really have to change your "train" or "augment" script... found no other solution...

**Comment by catpereira** [comment]
I already solved that with this code: https://github.com/sushantag9/image-segmentation-keras   , which is a branch of the one previously used.
