### ISSUE TITLE
Assertion error at LoadBatches.py for training

### ISSUE THREAD

**Issue by matheuscass** [divamgupta/image-segmentation-keras#35]
I'm having the following error: /LoadBatches.py", line 71, in imageSegmentationGenerator
    assert(  im.split('/')[-1].split(".")[0] ==  seg.split('/')[-1].split(".")[0] )
AssertionError

Any thoughts? =(

**Comment by giomhugo** [comment]
Am I right when I say you are on windows?

**Comment by matheuscass** [comment]
Yes, I'm on windows. I did the following (after aplying the modification you suggested):
print(im)
print(seg)

and that was the response:

data/dataset1/images_prepped_test\0016E5_08159.png
data/dataset1/annotations_prepped_test\0016E5_08159.png
data/dataset1/images_prepped_train\0016E5_08640.png
data/dataset1/annotations_prepped_train\0016E5_08640.png

**Comment by giomhugo** [comment]
So it worked?

**Comment by matheuscass** [comment]
Now I'm having this error:
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    m.fit_generator( G , 512  , validation_data=G2 , validation_steps=200 ,  epochs=1 )
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Matheus\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\Matheus\Desktop\UFRGS\Mestrado\tutorial_python\APLICACAO_A_AGRICULTURA\image-segmentation-keras-master\LoadBatches.py", line 82, in imageSegmentationGenerator
    im , seg = zipped.next()
AttributeError: 'itertools.cycle' object has no attribute 'next'

=(

**Comment by matheuscass** [comment]
I made the modification you mentioned, I think that assertion error is ok now, but I'm having this new error I've just mentioned above =(

**Comment by giomhugo** [comment]
Ok that error is because you are on python 3.X
modification : 
itertools.cycle().next() to next(itertools.cycle())

**Comment by matheuscass** [comment]
It worked! thanks a lot for your time!!! I'm rookie on python, so it's kind of hard to solve these errors on my own... I want to use the code to apply to my own dataset, so it's likely I'll need help again...

Thanks again!

**Comment by giomhugo** [comment]
You're very welcome !
If you ever have a problem or an error just type it in google and you will surely find solutions :p

**Comment by matheuscass** [comment]
Could you answer one more question? The instructions by the author tell us to use --input_height = 320 and --input_width = 640, but these are not the exact dimensions of the images from the dataset. How those value influence on the code?

**Comment by giomhugo** [comment]
For me, they cause an error for me ! I removed these arguments
Sorry can't help you on that :(

**Comment by divamgupta** [comment]
@matheuscass  there are multiple reasons that we do not use the original size of the images. If the images are very large, the the size of the CNN would also increase which means slower training time and more memory. In most cases, larger the image, you would have to  use more number of layers.

**Comment by giomhugo** [comment]
@divamgupta 
Let’s say my dataset are images of same dimensions (weird ratio 624*464) but the images I want to predict come from a phone (so dimensions like 1080p). What’s should I modify in order to get good dimensions on the prediction ?

**Comment by divamgupta** [comment]
You can first resize the image before inputting to the model and resize the output to the original dimensions
