### ISSUE TITLE
Error when running colab example. 

### ISSUE THREAD

**Issue by piperod** [divamgupta/image-segmentation-keras#350]
I am getting this error when trying to run the example on colab. 
AttributeError: module 'keras.utils' has no attribute 'get_file'
Any help or lead, very welcome.

**Comment by subramanyakrishna** [comment]
Please use below google colab link to solve this issue
https://colab.research.google.com/drive/17alEj52QYGNB1sxNFL96BoaI-weMnpYM?usp=sharing

**Comment by piperod** [comment]
It seems what is breaking the previous example  is the keras version. I forced it to 2.4 and tf 2.4 and it worked. Thanks anyways for the example!

**Comment by divamgupta** [comment]
This has been fixed now.
