### ISSUE TITLE
Data augmentation. Does it artificially expand the dataset?

### ISSUE THREAD

**Issue by chan-wm** [divamgupta/image-segmentation-keras#358]
Having read through the code, I thought that "IMAGE_AUGMENTATION_NUM_TRIES = 10" from "https://github.com/divamgupta/image-segmentation-keras/blob/master/keras_segmentation/data_utils/augmentation.py" might indicate the number of augmented images generated from one single original image. However, I don't think that this is the case. Could someone confirm if the dataset is expanded or  does it still stay the same size. I can see that the images fed in are augmented but I don't think the dataset size is increased.

**Comment by divamgupta** [comment]
The augmentation happens during training time for all the training batches. The image is augmented on every minibatch of training.
