### ISSUE TITLE
Multiclass Segmentation

### ISSUE THREAD

**Issue by omerfguzel** [divamgupta/image-segmentation-keras#362]
Hi,
This question may compromise that I'm a brand new rookie in segmentation :) 
I need to implement multiclass segmentation for a project. So I have images and annotation images of 5 classes. I implemented binary segmentation succesfully using kreas-segmentation. But how can I implement multiclass with this module? Where should I put the different class annotations?

**Comment by alastair5924** [comment]
I would also love to know the answer to this! I have a multiclass segmentation problem with 6 classes that I have been previously one-hot-encoding the classes into a (height, width,6) training sample.

**Comment by divamgupta** [comment]
You dont need other_inputs_paths for standard mulit-class segmentation. You just need to make annotation images with pixel value as class ID. See the sample dataset and the  code example in the readme.
