### ISSUE TITLE
What are the 50 class names? n_classes=50

### ISSUE THREAD

**Issue by sachinkmohan** [divamgupta/image-segmentation-keras#365]
Thanks for a wonderful repository @divamgupta ! :) 

I used `visualize_dataset.py` to view the dataset. The class numbers are displayed in numbers as below.
```
Found the following classes in the segmentation image: [ 0  1  2  3  5  6  8  9 11]
```
But where can I find what this class name corresponds to like car, person etc.. Any help would be appreciated.

**Comment by LaBiXiaoChai** [comment]
The author may use CamVid data set, you can find 33 categories on its official website。

And you don't need to know the number corresponding to the category，because the color on the labeled images can be distinguished  them。

**Comment by sachinkmohan** [comment]
Thanks! @LaBiXiaoChai
