### ISSUE TITLE
Getting accuracy and loss on test set

### ISSUE THREAD

**Issue by LukeGrixti** [divamgupta/image-segmentation-keras#369]
Hi, thank you for creating this repository @divamgupta!

I am struggling to see if there are any defined functions, apart from the one that ships with Keras, which get the accuracy and loss metrics on the test set from the dataset. Could you advise me, please?

If there isn't one, how can I define the 'x' and 'y' to use model.evaluate(x, y) from Keras?

Thanks :)

**Comment by divamgupta** [comment]
You can use the evaluate functionality 

```
python -m keras_segmentation evaluate_model \
 --checkpoints_path="path_to_checkpoints" \
 --images_path="dataset1/images_prepped_test/" \
 --segs_path="dataset1/annotations_prepped_test/"
```
