### ISSUE TITLE
Image segmentation version issues

### ISSUE THREAD

**Issue by jaigsingla** [divamgupta/image-segmentation-keras#373]
Hi
I was using vgg _unet model from old build and getting fair results but recently upgraded to cuda 10.1 and keras 2.4 tensorflow 2.2 and latest version of image segmentation. Surprisingly, vgg_unet with new implementation is not producing comparable results . Pls suggest if it further requires any update

**Comment by divamgupta** [comment]
That should not happen. The colab example with the latest version of keras / tf seems to give similar results as old version.
