### ISSUE TITLE
Request for Adding Link to the Public Repository

### ISSUE THREAD

**Issue by sadia-pma** [divamgupta/image-segmentation-keras#374]
Hi, Thank you so much for the repository!

This helped me a lot with my assignment, for my assignment I just cloned and ran the repository. When I was trying to train my dataset, I encountered an issue **AttributeError: module 'keras.utils' has no attribute 'get_file'**. The problem was solved by replacing **keras.utils** with **tensorflow.keras.utils**.

Further, I wanted to request for adding the link to my public repository in the Readme file of your repository as suggested by you. The link to my repository is **https://github.com/imsadia/cv-assignment-three.git**

**Comment by divamgupta** [comment]
Thanks
