### ISSUE TITLE
ValueError: You are trying to load a weight file containing 16 layers into a model with 19 layers.

### ISSUE THREAD

**Issue by JhonatanEstabile** [divamgupta/image-segmentation-keras#38]
This error happens when i call the function "m.load_weights(load_weights)"  in train.py file, how can I fix it ?
ps: I'm using the keras 2.2.2 version.

**Comment by Miranda1994** [comment]
you can change the " m.load_weights(  "/home/miranda/competition_OPPO/image-segmentation-keras/vgg16_weights_th_dim_ordering_th_kernels.h5") " to " m.load_weights(  "/home/miranda/competition_OPPO/image-segmentation-keras/vgg16_weights_th_dim_ordering_th_kernels.h5" ,by_name=True ) "

**Comment by sleach3** [comment]
@Miranda1994 I don't believe that solves the issue of loading in weights after you have trained the network and saved out the weights.

**Comment by appleandhero** [comment]
vgg16_weights_th_dim_ordering_th_kernels.h5 is 19 layers，but vgg16_weights_th_dim_ordering_th_kernels_notop.h5 is 16 layers

**Comment by divamgupta** [comment]
Image segmentation keras has been updated. The new version should fix the issue.
