### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lewisazhe** [divamgupta/image-segmentation-keras#40]
When training the model getting following error：
azhe@GTX1080Ti:~/projects/segmentation$ THEANO_FLAGS=device=cuda,floatX=float32 python train.py --save_weights_path=weights/export_unet --train_images="data/dataset/train/" --train_annotations="data/dataset/train_label/" --val_images="data/dataset/val/" --val_annotations="data/dataset/val_label/" --n_classes=256 --input_height=512 --input_width=512 --model_name='vgg_unet'
/home/azhe/anaconda3/lib/python3.6/site-packages/h5py/init.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
Using Theano backend.
Using cuDNN version 7003 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:01:00.0)
Model output shape (None, 65536, 256)
Epoch 1/1
Segmentation fault (core dumped)

How to solve it，can you help me？

**Comment by omrylcn** [comment]
you should down  tensorflow version to  <= 1.5

**Comment by divamgupta** [comment]
Image segmentation keras has been updated with tensorflow support. This should fix the issue.
