### ISSUE TITLE
why：“for ep in range( epochs )：”

### ISSUE THREAD

**Issue by HardworkingProgramer** [divamgupta/image-segmentation-keras#45]
Are they equal between  “for ep in range( epochs ):
	                                  m.fit_generator( G , 512  , epochs=1 )”    
                                 and “m.fit_generator( G , 512  , epochs=epochs  )” ？

**Comment by basgro** [comment]
The first is used to save the weights from every epoch, the latter can save the weights from the last epoch only.

**Comment by HardworkingProgramer** [comment]
well，I know. thank you very much.
