### ISSUE TITLE
OOM when allocating tensor with shape[7,7,512,4096].

### ISSUE THREAD

**Issue by hello1010101010101world** [divamgupta/image-segmentation-keras#46]
I attempted to use tensorflow backend. I changed "channel first " to "channel last " and "outputHeight2 = o_shape2[2] outputWidth2 = o_shape2[3]" to "outputHeight2 = o_shape2[1]  outputWidth2 = o_shape2[2]",however ,I got  one error that is "OOM when allocating tensor with shape[7,7,512,4096]." even though I make train batch only one picture on model fcn8 and fcn32. But when run on model vggunet it worked.  Is it because my graphics card memory is not big enough? It is 5G size.

**Comment by basgro** [comment]
What is the output of nvidia-smi before you start? And can you post the full output?

**Comment by PanPan0210** [comment]
@hello1010101010101world 
hello ,now i have the same problem .could  you tell me how to solve this question ?
 thank you

**Comment by divamgupta** [comment]
Try reducing the batch size or the image size.
