### ISSUE TITLE
train my own data

### ISSUE THREAD

**Issue by Ysoleil** [divamgupta/image-segmentation-keras#54]
Hello, this project is really nice for me. But i have my own dataset.
I want to know what i should do if i want to train my own dataset with your project.
For example,what kind of label should i have?
Thank u very much!
@divamgupta

**Comment by MjdMahasneh** [comment]
try reading the readme file (main page) section 'Preparing the data for training' they also provide a nice simple code to explain the labeling method.

**Comment by srinivas1746** [comment]
Hi @MjdMahasneh @divamgupta  ,

I have doubt regarding training own dataset.

where can i give the class label name for training.

Thanks and regards.
