### ISSUE TITLE
ImportError: cannot import name 'merge'

### ISSUE THREAD

**Issue by navya002** [divamgupta/image-segmentation-keras#55]
I am using theano as backend and  downgraded keras to version 2.0 but still the merge function is not being imported from `keras.layers.core`. It throws the following error: `ImportError: cannot import name 'merge'.`

Tried calling it  from `keras.layer` and it did not show any import errors but as soon as the merge function was called it gave an error: `module not callable`

Please Help!

**Comment by divamgupta** [comment]
Image segmentation keras has been updated. The new version should fix the issue.
