### ISSUE TITLE
No module named 'keras_segmentation'

### ISSUE THREAD

**Issue by lahorekid** [divamgupta/image-segmentation-keras#57]
Using python 2
IDE: Google Colab

code:

 !git clone https://github.com/divamgupta/image-segmentation-keras

import keras_segmentation
​
model = keras_segmentation.pretrained.resnet_pspnet_VOC12_v0_1() # load the pretrained model
​
out = model.predict_segmentation(
    inp="voc_prepped/images_prepped_test/2007_000738.jpg",
    out_fname="out.png"
)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-0955581b93cb> in <module>()
      1 
----> 2 import keras_segmentation
      3 
      4 model = keras_segmentation.pretrained.resnet_pspnet_VOC12_v0_1() # load the pretrained model
      5 

ModuleNotFoundError: No module named 'keras_segmentation'

How do i install keras_segmentation'? There is no pip for it.

**Comment by divamgupta** [comment]
run : python setup.py install
