### ISSUE TITLE
Change the values of input_height and input_width.ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 10, 10, 256), (None, 10, 10, 512), (None, 10, 10, 512), (None, 12, 12, 512), (None, 10, 10, 512)]

### ISSUE THREAD

**Issue by YuanZYF** [divamgupta/image-segmentation-keras#58]

**Comment by divamgupta** [comment]
Which model with what configuration is giving this error. Could you give the snippet / command to reproduce this error?

**Comment by YuanZYF** [comment]
import keras_segmentation

model = keras_segmentation.models.pspnet.pspnet(21, input_height=320, input_width=320 )
model.summary()

**Comment by divamgupta** [comment]
For PSPNet the width and height should be a multiple of 192 and there is an assert statement [here](https://github.com/divamgupta/image-segmentation-keras/blob/master/keras_segmentation/models/pspnet.py#L50) to prevent that.

**Comment by YuanZYF** [comment]
How do I change the code so that the input is 320？

**Comment by divamgupta** [comment]
Appropriate padding should be added in the conv layers such that the shapes match.
