### ISSUE TITLE
Is the evaluate function in predict.py working?

### ISSUE THREAD

**Issue by saramsv** [divamgupta/image-segmentation-keras#60]
What is the reason for 'assert False , "not implemented "' in predict.py. It seems the iou is correctly calculated? Am I missing something?

**Comment by divamgupta** [comment]
I have not tested it thoroughly  yet.

**Comment by AmeetR** [comment]
@saramsv  Have you gotten this function to work? I'm having someweird results when I take that code and fix it so it works

**Comment by lakshmankanakala** [comment]
Hi @AmeetR, What are the fixes you have done in evaluate function for finding metrics . Can you tell me or share the code snippet.

**Comment by AmeetR** [comment]
@lakshmankanakala  I can share the code snippet if you really want, but it was just some file processing stuff. I put it into a jupyter notebook and fiddled with the file io until it worked, but the logic is all still there. However, this is still not working as of yet.

**Comment by lakshmankanakala** [comment]
Are saying, the code is not correct or what ? I have not understood fully what you said. Can please you tell me somewhat clearly.

**Comment by singaloo** [comment]
so do you know how to fix the code? Can you share the code snippet?

**Comment by zdd0819** [comment]
> @lakshmankanakala I can share the code snippet if you really want, but it was just some file processing stuff. I put it into a jupyter notebook and fiddled with the file io until it worked, but the logic is all still there. However, this is still not working as of yet.

hi, can u share your code about the evaluate function with me. I tried much times but still cannot work. Thank you very much! email:465118053@qq.com
