### ISSUE TITLE
Use MobileNet encoder in PSPNet? 

### ISSUE THREAD

**Issue by shen338** [divamgupta/image-segmentation-keras#65]
Hi: 

Thank you for this awesome repo. 

I need MobileNet as encoder for speed purposes. But I find out this part of code is commented out in keras_segmentation/models/pspnet.py. Before I try, could you please tell me if there is something wrong with it? 

Thank you!

**Comment by divamgupta** [comment]
Mobilenet with PSPNet is not supported yet. You can use MobileNet with unet as it might give similar results.
