### ISSUE TITLE
how can i get the prediction picture?

### ISSUE THREAD

**Issue by zdd0819** [divamgupta/image-segmentation-keras#66]
when i input the "python -m keras_segmentation predict \
>  --checkpoints_path="path_to_checkpoints" \
>  --input_path="dataset1/images_prepped_test/" \
>  --output_path="path_to_predictions"
"
i can't find any result, so how can i get the img result?
many thanks~

**Comment by zdd0819** [comment]
ok i find my fault ,it the problem of address.

by the way, if i want to use the nyu v2 data set, how should i choose the model?

**Comment by divamgupta** [comment]
You can try fine-tuning from `keras_segmentation.pretrained.pspnet_50_ADE_20K`
