### ISSUE TITLE
color coding about Output Segmentation Image

### ISSUE THREAD

**Issue by xunhs** [divamgupta/image-segmentation-keras#67]
Excuse me, how can I get the color coding about the output segmentation image? Thanks.

**Comment by divamgupta** [comment]
The class colors are defined [here](https://github.com/divamgupta/image-segmentation-keras/blob/master/keras_segmentation/predict.py#L21)

**Comment by xunhs** [comment]
So the color defined using random function. I mean I will not know which color represent specific item (e.g., sky)? Thank you very much~

**Comment by divamgupta** [comment]
Before pre-computing the colors the random seed has been set to zero. Hence the mappings of class ID to colors would be deterministic. The mappings of the class name to class ID should can be at the dataset

**Comment by zdd0819** [comment]
> Before pre-computing the colors the random seed has been set to zero. Hence the mappings of class ID to colors would be deterministic. The mappings of the class name to class ID should can be at the dataset

so where can i find that?

**Comment by divamgupta** [comment]
You can print the list of the colors after they are computed.
