### ISSUE TITLE
use gpu to train

### ISSUE THREAD

**Issue by zdd0819** [divamgupta/image-segmentation-keras#74]
when i use the cuda and tensorflow-gpu to train my model, it show that the Gpu utilization is0 and the speed is als slow.

do u know what's problem about that? do i need change any code?
<img width="574" alt="未命名" src="https://user-images.githubusercontent.com/39216094/60308076-2a1c5500-993f-11e9-99a7-e4465664b58f.png">
<img width="669" alt="333" src="https://user-images.githubusercontent.com/39216094/60308096-3f917f00-993f-11e9-9358-c200ba99803c.png">

and my parameters are:
 --n_classes=38 \
 --input_height=320 \
 --input_width=640 \
 --epochs=100\
 --batch_size=32\
 --steps_per_epoch=256\
 --model_name="fcn_8"

**Comment by divamgupta** [comment]
No changes in the code are needed. It is possible that tensorflow-gpu is not installed correctly.
