### ISSUE TITLE
training checkpoints_point _config.json error 

### ISSUE THREAD

**Issue by jaigsingla** [divamgupta/image-segmentation-keras#79]
![image001](https://user-images.githubusercontent.com/25918360/60580598-ff992480-9da2-11e9-913a-01e0a4361c9a.jpg)

facing no such file or directory : _config.json while using checkpoints_path in training command.

**Comment by divamgupta** [comment]
That is weird. This error should only occur if `../dataset1/checkpoints_point/` does not exist relative to the current working directory.

**Comment by jaigsingla** [comment]
It is throwing error on line no 68 of train.py asking for file input.  Where is this file _config.json

**Comment by divamgupta** [comment]
Line number 68 : `open( checkpoints_path+"_config.json" , "w" ).write(` should create a file named _config.json . The error will come if `checkpoints_path` does not exist.

**Comment by jaigsingla** [comment]
OK.  Will check this again.

**Comment by jaigsingla** [comment]
There was relative path mistake .
