### ISSUE TITLE
Cannot open image to segment using pre-trained model, get `AttributeError: 'NoneType' object has no attribute 'shape'`

### ISSUE THREAD

**Issue by iboates** [divamgupta/image-segmentation-keras#80]
I'm trying to just segment my own image using one of the pretrained models (ADE20k to be exact) but it seems to be unable to open the image, because I get the error in the title. I'm using Google Colab, and this is my code:

```
# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

!pip install keras-segmentation

import keras_segmentation
model = keras_segmentation.pretrained.pspnet_50_ADE_20K() # load the pretrained model trained on ADE20k dataset

out = model.predict_segmentation(
    inp="content/cafe.png",
    out_fname="content/out.png"
)

`cafe.png` is the path to the image as it appears when I copy the file directly from the file browser. Am I doing something wrong?
```

**Comment by divamgupta** [comment]
The path `content/cafe.png` probably does not exist. To check if the file exist, `os.path.isfile("content/cafe.png")` should return True.

**Comment by iboates** [comment]
It turns out that the problem is that the path that you copy from Google Colab is actually not the path to the file... Which I find quite bizarre. Once I removed `content/`, it worked. Sorry about that, it has nothing to do with the repo.
