### ISSUE TITLE
How to use callbacks like earlystoping?

### ISSUE THREAD

**Issue by HeliumTang** [divamgupta/image-segmentation-keras#86]
How to use callbacks when train on my own datasets from scratch? Thanks.

model = keras_segmentation.models.unet.vgg_unet(n_classes=2, 
                                                input_height=416,
                                                input_width=608)

model.train(
    train_images="data/train/",
    train_annotations="data/train_masks/",
    checkpoints_path = "/tmp/vgg_unet_1",
    epochs=5,
    verify_dataset=False,
)

**Comment by SharifElfouly** [comment]
I would just change the train.py in /keras_segmentation and add your callback in the model.fit_generator() method.
