### ISSUE TITLE
OP_kernel.cc error in case of 2048 x 2048 image training 

### ISSUE THREAD

**Issue by jaigsingla** [divamgupta/image-segmentation-keras#95]
I have training set of 13 images of  2048x 2048 size. while executing predict module getting error of OP_Requires failed at conv_grad_input_ops.cc : 942. Resource exhausted. I am working on a GPU with 24 GB memory.

**Comment by divamgupta** [comment]
Having a large input size would need a lot of GPU memory. Hence you are getting the memory error. 
Training the models with high resolution is not a good idea. A good size would be around 500x500.
