### ISSUE TITLE
loading json files and running the model again 

### ISSUE THREAD

**Issue by jaigsingla** [divamgupta/image-segmentation-keras#98]
Dear Divam, 

Is there any way to load existing json files and then train for rest of epochs. Suppose json file is saved after 50 epochs but now i want to run  model for 100 epochs . Can I make use of existing json files in this case ? How to do this ?

**Comment by divamgupta** [comment]
You can use `model_from_checkpoint_path` function which is defined [here](https://github.com/divamgupta/image-segmentation-keras/blob/master/keras_segmentation/predict.py#L24).
